In [1]:
## Importing Libraries
import numpy as np
import pandas as pd

In [2]:
## Reading Data
df = pd.read_csv('training.csv')
df

id  category                                               text
0      959         0    5573 1189 4017 1207 4768 8542 17 1189 5085 5773
1      994         0       6315 7507 6700 4742 1944 2692 3647 4413 6700
2      995         0                      5015 8067 5335 1615 7957 5773
3      996         0  2925 7199 1994 4647 7455 5773 4518 2734 2807 8...
4      997         0                  7136 1207 6781 237 4971 3669 6193
...    ...       ...                                                ...
3459  4851         1  6787 5435 3515 3324 3477 7337 4234 4328 7606 5...
3460  4852         1  6787 5983 5922 1577 5658 3718 1530 4801 5658 7...
3461  4853         1  6787 3359 4108 5007 3477 4909 5342 224 6663 64...
3462  4854         1  6787 3917 4017 5573 5979 4457 4108 1226 4332 1...
3463  4855         1  6787 636 4017 8618 5941 7410 1352 5239 753 646...

[3464 rows x 3 columns]

In [3]:
x = [df["text"][0]]

In [4]:
y=df['category']

In [5]:
x[0].replace("''",'')

'5573 1189 4017 1207 4768 8542 17 1189 5085 5773'

In [6]:
import re

s = re.findall(r'\d+', x[0])

s

['5573', '1189', '4017', '1207', '4768', '8542', '17', '1189', '5085', '5773']

In [7]:
import ast
[ast.literal_eval(i) for i in s]

[5573, 1189, 4017, 1207, 4768, 8542, 17, 1189, 5085, 5773]

In [8]:
text = []
for i in range(len(df)):
    text.append(re.findall(r'\d+',df["text"][i]))
text    

[['5573',
  '1189',
  '4017',
  '1207',
  '4768',
  '8542',
  '17',
  '1189',
  '5085',
  '5773'],
 ['6315', '7507', '6700', '4742', '1944', '2692', '3647', '4413', '6700'],
 ['5015', '8067', '5335', '1615', '7957', '5773'],
 ['2925',
  '7199',
  '1994',
  '4647',
  '7455',
  '5773',
  '4518',
  '2734',
  '2807',
  '853',
  '8542',
  '2283',
  '753',
  '5107',
  '5922',
  '4355',
  '6054',
  '4608',
  '2199',
  '142',
  '4211',
  '8103',
  '5773',
  '7747'],
 ['7136', '1207', '6781', '237', '4971', '3669', '6193'],
 ['6730',
  '3349',
  '2325',
  '7714',
  '5773',
  '5172',
  '6254',
  '4097',
  '6500',
  '6927',
  '5107',
  '5045',
  '5773',
  '3533',
  '3255',
  '6254',
  '3225',
  '2325',
  '6110',
  '6912',
  '7732',
  '3283',
  '2698',
  '220',
  '8431',
  '2641',
  '753',
  '5773',
  '4122',
  '4675',
  '5175',
  '8465',
  '5395',
  '5703',
  '4297',
  '6794',
  '5773'],
 ['714', '4164', '5672', '8124'],
 ['7674', '4947', '7671', '4335', '1587', '6589', '3669', '6254', '6517'],
 

In [9]:
import ast
text_new = []
for i in range(len(df)):
    text_new.append([ast.literal_eval(j) for j in text[i]])
text_new  

[[5573, 1189, 4017, 1207, 4768, 8542, 17, 1189, 5085, 5773],
 [6315, 7507, 6700, 4742, 1944, 2692, 3647, 4413, 6700],
 [5015, 8067, 5335, 1615, 7957, 5773],
 [2925,
  7199,
  1994,
  4647,
  7455,
  5773,
  4518,
  2734,
  2807,
  853,
  8542,
  2283,
  753,
  5107,
  5922,
  4355,
  6054,
  4608,
  2199,
  142,
  4211,
  8103,
  5773,
  7747],
 [7136, 1207, 6781, 237, 4971, 3669, 6193],
 [6730,
  3349,
  2325,
  7714,
  5773,
  5172,
  6254,
  4097,
  6500,
  6927,
  5107,
  5045,
  5773,
  3533,
  3255,
  6254,
  3225,
  2325,
  6110,
  6912,
  7732,
  3283,
  2698,
  220,
  8431,
  2641,
  753,
  5773,
  4122,
  4675,
  5175,
  8465,
  5395,
  5703,
  4297,
  6794,
  5773],
 [714, 4164, 5672, 8124],
 [7674, 4947, 7671, 4335, 1587, 6589, 3669, 6254, 6517],
 [326,
  4211,
  8380,
  7343,
  6084,
  779,
  8542,
  3485,
  5141,
  3078,
  1976,
  4108,
  5922,
  5439,
  4973,
  224,
  4442,
  7792,
  5893],
 [6546, 6949, 1309, 528, 784, 5773],
 [7879, 3385, 230, 7350, 2963, 7473, 5773, 4

In [11]:
# l = []
# for i in range(len(text_new)):
#     l.append(len(text_new[i]))   

6290

In [14]:
np.median(l)

13.0

In [13]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [15]:
text_new

[[5573, 1189, 4017, 1207, 4768, 8542, 17, 1189, 5085, 5773],
 [6315, 7507, 6700, 4742, 1944, 2692, 3647, 4413, 6700],
 [5015, 8067, 5335, 1615, 7957, 5773],
 [2925,
  7199,
  1994,
  4647,
  7455,
  5773,
  4518,
  2734,
  2807,
  853,
  8542,
  2283,
  753,
  5107,
  5922,
  4355,
  6054,
  4608,
  2199,
  142,
  4211,
  8103,
  5773,
  7747],
 [7136, 1207, 6781, 237, 4971, 3669, 6193],
 [6730,
  3349,
  2325,
  7714,
  5773,
  5172,
  6254,
  4097,
  6500,
  6927,
  5107,
  5045,
  5773,
  3533,
  3255,
  6254,
  3225,
  2325,
  6110,
  6912,
  7732,
  3283,
  2698,
  220,
  8431,
  2641,
  753,
  5773,
  4122,
  4675,
  5175,
  8465,
  5395,
  5703,
  4297,
  6794,
  5773],
 [714, 4164, 5672, 8124],
 [7674, 4947, 7671, 4335, 1587, 6589, 3669, 6254, 6517],
 [326,
  4211,
  8380,
  7343,
  6084,
  779,
  8542,
  3485,
  5141,
  3078,
  1976,
  4108,
  5922,
  5439,
  4973,
  224,
  4442,
  7792,
  5893],
 [6546, 6949, 1309, 528, 784, 5773],
 [7879, 3385, 230, 7350, 2963, 7473, 5773, 4

In [16]:
voc_size = 10000

In [17]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [18]:
sent_length=40
embedded_docs=pad_sequences(text_new,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 1189 5085 5773]
 [   0    0    0 ... 3647 4413 6700]
 [   0    0    0 ... 1615 7957 5773]
 ...
 [   0    0    0 ... 5773 5177 5225]
 [   0    0    0 ... 3738 2014  154]
 [   0    0    0 ... 3978 1377 3226]]


In [19]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0, 5573, 1189, 4017,
       1207, 4768, 8542,   17, 1189, 5085, 5773])

In [20]:
embedding_vector_features=40
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(100)))
model1.add(Dropout(0.3))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 40, 40)            400000    
_________________________________________________________________
bidirectional (Bidirectional (None, 200)               112800    
_________________________________________________________________
dropout (Dropout)            (None, 200)               0         
_________________________________________________________________
dense (Dense)                (None, 1)                 201       
Total params: 513,001
Trainable params: 513,001
Non-trainable params: 0
_________________________________________________________________
None


In [21]:
len(embedded_docs),y.shape

(3464, (3464,))

In [22]:
y.value_counts()

0    3348
1     116
Name: category, dtype: int64

In [23]:

import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [24]:
X_final.shape,y_final.shape

((3464, 40), (3464,))

In [25]:
negative = df[df['category']==1]

In [26]:
positive = df[df['category']==0]

In [27]:
print(negative.shape,positive.shape)

(116, 3) (3348, 3)


In [28]:
from imblearn.over_sampling import RandomOverSampler

C:\Users\aakas\Anaconda\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [29]:
os = RandomOverSampler()

In [30]:
X_train_res, y_train_res = os.fit_sample(X_final, y_final)

In [31]:
X_train_res.shape,y_train_res.shape

((6696, 40), (6696,))

In [32]:
from collections import Counter
print('Original dataset shape {}'.format(Counter(y_final)))
print('Resampled dataset shape {}'.format(Counter(y_train_res)))

Original dataset shape Counter({0: 3348, 1: 116})
Resampled dataset shape Counter({0: 3348, 1: 3348})


In [33]:
df1 = pd.read_csv('test_.csv')

In [34]:
X = [df1["text"][0]]

In [35]:
X[0].replace("''",'')

'2705 4888 5050 5815 2472 5157 652 2117 2110 325 4462 5931 1177 1911 1177 2084 1177 5094 1177 999 1873 5663 4284 3115 2267 1631 4803 899 5936'

In [36]:
import re

p = re.findall(r'\d+', X[0])

p

['2705',
 '4888',
 '5050',
 '5815',
 '2472',
 '5157',
 '652',
 '2117',
 '2110',
 '325',
 '4462',
 '5931',
 '1177',
 '1911',
 '1177',
 '2084',
 '1177',
 '5094',
 '1177',
 '999',
 '1873',
 '5663',
 '4284',
 '3115',
 '2267',
 '1631',
 '4803',
 '899',
 '5936']

In [37]:
import ast
[ast.literal_eval(i) for i in p]

[2705,
 4888,
 5050,
 5815,
 2472,
 5157,
 652,
 2117,
 2110,
 325,
 4462,
 5931,
 1177,
 1911,
 1177,
 2084,
 1177,
 5094,
 1177,
 999,
 1873,
 5663,
 4284,
 3115,
 2267,
 1631,
 4803,
 899,
 5936]

In [38]:
text1 = []
for i in range(len(df1)):
    text1.append(re.findall(r'\d+',df1["text"][i]))
text1   

[['2705',
  '4888',
  '5050',
  '5815',
  '2472',
  '5157',
  '652',
  '2117',
  '2110',
  '325',
  '4462',
  '5931',
  '1177',
  '1911',
  '1177',
  '2084',
  '1177',
  '5094',
  '1177',
  '999',
  '1873',
  '5663',
  '4284',
  '3115',
  '2267',
  '1631',
  '4803',
  '899',
  '5936'],
 ['389',
  '4978',
  '315',
  '5178',
  '513',
  '5249',
  '5853',
  '3267',
  '315',
  '3891',
  '5465',
  '652',
  '2543',
  '2642',
  '4126',
  '5179',
  '1460',
  '5384',
  '4747',
  '5120',
  '1867',
  '4699',
  '623',
  '4921',
  '5178',
  '1311',
  '1026'],
 ['4478',
  '4231',
  '4858',
  '2638',
  '4231',
  '867',
  '371',
  '686',
  '4888',
  '4179',
  '5886',
  '2272',
  '5097',
  '1409',
  '3239',
  '5631',
  '5178',
  '1809',
  '4757',
  '5587',
  '899',
  '3126',
  '4185',
  '1177',
  '4030',
  '1273',
  '3891',
  '3500',
  '5178',
  '1605'],
 ['3015',
  '1911',
  '112',
  '3905',
  '825',
  '337',
  '315',
  '1693',
  '4677',
  '825',
  '5269',
  '3319',
  '3154',
  '132'],
 ['5136',
  '391

In [39]:
import ast
text_new1 = []
for i in range(len(df1)):
    text_new1.append([ast.literal_eval(j) for j in text1[i]])
text_new1

[[2705,
  4888,
  5050,
  5815,
  2472,
  5157,
  652,
  2117,
  2110,
  325,
  4462,
  5931,
  1177,
  1911,
  1177,
  2084,
  1177,
  5094,
  1177,
  999,
  1873,
  5663,
  4284,
  3115,
  2267,
  1631,
  4803,
  899,
  5936],
 [389,
  4978,
  315,
  5178,
  513,
  5249,
  5853,
  3267,
  315,
  3891,
  5465,
  652,
  2543,
  2642,
  4126,
  5179,
  1460,
  5384,
  4747,
  5120,
  1867,
  4699,
  623,
  4921,
  5178,
  1311,
  1026],
 [4478,
  4231,
  4858,
  2638,
  4231,
  867,
  371,
  686,
  4888,
  4179,
  5886,
  2272,
  5097,
  1409,
  3239,
  5631,
  5178,
  1809,
  4757,
  5587,
  899,
  3126,
  4185,
  1177,
  4030,
  1273,
  3891,
  3500,
  5178,
  1605],
 [3015,
  1911,
  112,
  3905,
  825,
  337,
  315,
  1693,
  4677,
  825,
  5269,
  3319,
  3154,
  132],
 [5136,
  3918,
  5153,
  2023,
  3091,
  4159,
  315,
  3711,
  1409,
  2730,
  1177,
  30,
  2031,
  2730,
  4159,
  2372,
  4865,
  1177],
 [1235,
  3211,
  5420,
  4479,
  2743,
  3707,
  4934,
  2893,
  5600,
  

In [40]:
sent_length=40
embedded_docs1=pad_sequences(text_new1,padding='pre',maxlen=sent_length)
print(embedded_docs1)

[[   0    0    0 ... 4803  899 5936]
 [   0    0    0 ... 5178 1311 1026]
 [   0    0    0 ... 3500 5178 1605]
 ...
 [5566 2025 2703 ... 5779  888 4888]
 [   0    0    0 ... 3204 5262   51]
 [   0    0    0 ... 4937 3204 5120]]


In [41]:
embedded_docs1[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       2705, 4888, 5050, 5815, 2472, 5157,  652, 2117, 2110,  325, 4462,
       5931, 1177, 1911, 1177, 2084, 1177, 5094, 1177,  999, 1873, 5663,
       4284, 3115, 2267, 1631, 4803,  899, 5936])

In [42]:
import numpy as np
X_test=np.array(embedded_docs1)

In [43]:
X_test.shape

(1360, 40)

In [44]:

y_pred1=model1.predict_classes(X_test)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [45]:
y_pred1

array([[1],
       [1],
       [0],
       ...,
       [0],
       [1],
       [1]])

In [46]:
df3 = pd.DataFrame(data=y_pred1)
print(df3)



      0
0     1
1     1
2     0
3     1
4     1
...  ..
1355  1
1356  1
1357  0
1358  1
1359  1

[1360 rows x 1 columns]


In [47]:
# df3.to_csv("/content/drive/My Drive/Colab Notebooks/SKILLENZA/ML LEVEL 1/df3.csv")

In [48]:
# y_pred1.to_csv

In [49]:
df2 = pd.read_csv("sample_submission_.csv")

In [50]:
Y_test = df2['category']

In [51]:
model1.fit(X_train_res,y_train_res,validation_data=(X_test,Y_test),epochs=10,batch_size=64)

Epoch 1/10
105/105 [==============================] - 9s 81ms/step - loss: 0.1843 - accuracy: 0.9056 - val_loss: 4.9068 - val_accuracy: 0.0176
Epoch 2/10
105/105 [==============================] - 7s 71ms/step - loss: 0.0058 - accuracy: 0.9987 - val_loss: 6.0148 - val_accuracy: 0.0029
Epoch 3/10
105/105 [==============================] - 7s 68ms/step - loss: 0.0018 - accuracy: 0.9997 - val_loss: 7.5157 - val_accuracy: 0.0015
Epoch 4/10
105/105 [==============================] - 8s 74ms/step - loss: 4.9391e-04 - accuracy: 1.0000 - val_loss: 7.7354 - val_accuracy: 0.0015
Epoch 5/10
105/105 [==============================] - 8s 73ms/step - loss: 2.1456e-04 - accuracy: 1.0000 - val_loss: 8.3959 - val_accuracy: 0.0022
Epoch 6/10
105/105 [==============================] - 8s 73ms/step - loss: 1.1264e-04 - accuracy: 1.0000 - val_loss: 8.9544 - val_accuracy: 0.0022
Epoch 7/10
105/105 [==============================] - 7s 68ms/step - loss: 1.4742e-04 - accuracy: 1.0000 - val_loss: 9.2510 - val_

In [52]:
y_pred1 = model1.predict_classes(X_test)

In [53]:
from sklearn.metrics import confusion_matrix

In [54]:
confusion_matrix(Y_test,y_pred1)

array([[   0,    0],
       [1351,    9]], dtype=int64)

In [55]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred1)

0.006617647058823529

In [63]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       0.0
           1       0.00      0.00      0.00    1360.0

    accuracy                           0.00    1360.0
   macro avg       0.00      0.00      0.00    1360.0
weighted avg       0.00      0.00      0.00    1360.0



C:\Users\aakas\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\aakas\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [57]:
sample = pd.read_csv("sample_submission_.csv")
sample

id  category
0     3729         1
1     3732         1
2     3761         1
3        5         1
4        7         1
...    ...       ...
1355   311         1
1356   324         1
1357   329         1
1358   342         1
1359   352         1

[1360 rows x 2 columns]

In [58]:
##naive bayes

In [107]:
from sklearn.naive_bayes import MultinomialNB
model2 = MultinomialNB()
model2.fit(X_train_res, y_train_res)
model2.predict(X_test)
pd.DataFrame(model2.predict(X_test))
category_naive = sample
category_naive["category"] = pd.DataFrame(model2.predict(X_test))[0]
category_naive["category"].value_counts()

0    724
1    636
Name: category, dtype: int64

In [122]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression()
lg.fit(X_train_res, y_train_res)
lg.predict(X_test)
pd.DataFrame(lg.predict(X_test))
category_lg = sample
category_lg["category"] = pd.DataFrame(lg.predict(X_test))[0]
category_lg["category"].value_counts()

0    770
1    590
Name: category, dtype: int64

In [158]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(X_train_res, y_train_res)
dt.predict(X_test)
pd.DataFrame(dt.predict(X_test))
category_dt = sample
category_dt["category"] = pd.DataFrame(dt.predict(X_test))[0]
category_dt["category"].value_counts()

0    1255
1     105
Name: category, dtype: int64

In [67]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train_res, y_train_res)
rf.predict(X_test)
pd.DataFrame(rf.predict(X_test))
category_rf = sample
category_rf["category"] = pd.DataFrame(rf.predict(X_test))[0]
category_rf["category"].value_counts()

0    1340
1      20
Name: category, dtype: int64

In [142]:
from sklearn.svm import SVC
svm = SVC()
svm.fit(X_train_res, y_train_res)
svm.predict(X_test)
pd.DataFrame(svm.predict(X_test))
category_svm = sample
category_svm["category"] = pd.DataFrame(svm.predict(X_test))[0]
category_svm

id  category
0     3729         0
1     3732         0
2     3761         0
3        5         0
4        7         0
...    ...       ...
1355   311         0
1356   324         0
1357   329         0
1358   342         0
1359   352         0

[1360 rows x 2 columns]

In [143]:
category_naive.to_csv("D:\\Skillenza_Bootcamp\\ML Level1\\Problem1\\category_naive.csv")
category_lg.to_csv("D:\\Skillenza_Bootcamp\\ML Level1\\Problem1\\category_lg.csv")
category_dt.to_csv("D:\\Skillenza_Bootcamp\\ML Level1\\Problem1\\category_dt.csv")
category_svm.to_csv("D:\\Skillenza_Bootcamp\\ML Level1\\Problem1\\category_svm.csv")

In [159]:
category_dt.to_csv("D:\\Skillenza_Bootcamp\\ML Level1\\Problem1\\category_dt1.csv")