In [1]:
## Importing Libraries
import numpy as np
import pandas as pd

In [2]:
## Reading Data
df = pd.read_csv('training.csv')
df

id  category                                               text
0      959         0    5573 1189 4017 1207 4768 8542 17 1189 5085 5773
1      994         0       6315 7507 6700 4742 1944 2692 3647 4413 6700
2      995         0                      5015 8067 5335 1615 7957 5773
3      996         0  2925 7199 1994 4647 7455 5773 4518 2734 2807 8...
4      997         0                  7136 1207 6781 237 4971 3669 6193
...    ...       ...                                                ...
3459  4851         1  6787 5435 3515 3324 3477 7337 4234 4328 7606 5...
3460  4852         1  6787 5983 5922 1577 5658 3718 1530 4801 5658 7...
3461  4853         1  6787 3359 4108 5007 3477 4909 5342 224 6663 64...
3462  4854         1  6787 3917 4017 5573 5979 4457 4108 1226 4332 1...
3463  4855         1  6787 636 4017 8618 5941 7410 1352 5239 753 646...

[3464 rows x 3 columns]

In [3]:
x = [df["text"][0]]

In [4]:
y=df['category']

In [5]:
x[0].replace("''",'')

'5573 1189 4017 1207 4768 8542 17 1189 5085 5773'

In [6]:
import re

s = re.findall(r'\d+', x[0])

s

['5573', '1189', '4017', '1207', '4768', '8542', '17', '1189', '5085', '5773']

In [7]:
import ast
[ast.literal_eval(i) for i in s]

[5573, 1189, 4017, 1207, 4768, 8542, 17, 1189, 5085, 5773]

In [8]:
text = []
for i in range(len(df)):
    text.append(re.findall(r'\d+',df["text"][i]))
text    

[['5573',
  '1189',
  '4017',
  '1207',
  '4768',
  '8542',
  '17',
  '1189',
  '5085',
  '5773'],
 ['6315', '7507', '6700', '4742', '1944', '2692', '3647', '4413', '6700'],
 ['5015', '8067', '5335', '1615', '7957', '5773'],
 ['2925',
  '7199',
  '1994',
  '4647',
  '7455',
  '5773',
  '4518',
  '2734',
  '2807',
  '853',
  '8542',
  '2283',
  '753',
  '5107',
  '5922',
  '4355',
  '6054',
  '4608',
  '2199',
  '142',
  '4211',
  '8103',
  '5773',
  '7747'],
 ['7136', '1207', '6781', '237', '4971', '3669', '6193'],
 ['6730',
  '3349',
  '2325',
  '7714',
  '5773',
  '5172',
  '6254',
  '4097',
  '6500',
  '6927',
  '5107',
  '5045',
  '5773',
  '3533',
  '3255',
  '6254',
  '3225',
  '2325',
  '6110',
  '6912',
  '7732',
  '3283',
  '2698',
  '220',
  '8431',
  '2641',
  '753',
  '5773',
  '4122',
  '4675',
  '5175',
  '8465',
  '5395',
  '5703',
  '4297',
  '6794',
  '5773'],
 ['714', '4164', '5672', '8124'],
 ['7674', '4947', '7671', '4335', '1587', '6589', '3669', '6254', '6517'],
 

In [9]:
import ast
text_new = []
for i in range(len(df)):
    text_new.append([ast.literal_eval(j) for j in text[i]])
text_new  

[[5573, 1189, 4017, 1207, 4768, 8542, 17, 1189, 5085, 5773],
 [6315, 7507, 6700, 4742, 1944, 2692, 3647, 4413, 6700],
 [5015, 8067, 5335, 1615, 7957, 5773],
 [2925,
  7199,
  1994,
  4647,
  7455,
  5773,
  4518,
  2734,
  2807,
  853,
  8542,
  2283,
  753,
  5107,
  5922,
  4355,
  6054,
  4608,
  2199,
  142,
  4211,
  8103,
  5773,
  7747],
 [7136, 1207, 6781, 237, 4971, 3669, 6193],
 [6730,
  3349,
  2325,
  7714,
  5773,
  5172,
  6254,
  4097,
  6500,
  6927,
  5107,
  5045,
  5773,
  3533,
  3255,
  6254,
  3225,
  2325,
  6110,
  6912,
  7732,
  3283,
  2698,
  220,
  8431,
  2641,
  753,
  5773,
  4122,
  4675,
  5175,
  8465,
  5395,
  5703,
  4297,
  6794,
  5773],
 [714, 4164, 5672, 8124],
 [7674, 4947, 7671, 4335, 1587, 6589, 3669, 6254, 6517],
 [326,
  4211,
  8380,
  7343,
  6084,
  779,
  8542,
  3485,
  5141,
  3078,
  1976,
  4108,
  5922,
  5439,
  4973,
  224,
  4442,
  7792,
  5893],
 [6546, 6949, 1309, 528, 784, 5773],
 [7879, 3385, 230, 7350, 2963, 7473, 5773, 4

In [25]:
# l = []
# for i in range(len(text_new)):
#     l.append(len(text_new[i]))   

In [23]:
# pd.set_option("display.max_rows",None)
# pd.DataFrame(pd.DataFrame(l)[0].value_counts())

In [26]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [15]:
text_new

[[5573, 1189, 4017, 1207, 4768, 8542, 17, 1189, 5085, 5773],
 [6315, 7507, 6700, 4742, 1944, 2692, 3647, 4413, 6700],
 [5015, 8067, 5335, 1615, 7957, 5773],
 [2925,
  7199,
  1994,
  4647,
  7455,
  5773,
  4518,
  2734,
  2807,
  853,
  8542,
  2283,
  753,
  5107,
  5922,
  4355,
  6054,
  4608,
  2199,
  142,
  4211,
  8103,
  5773,
  7747],
 [7136, 1207, 6781, 237, 4971, 3669, 6193],
 [6730,
  3349,
  2325,
  7714,
  5773,
  5172,
  6254,
  4097,
  6500,
  6927,
  5107,
  5045,
  5773,
  3533,
  3255,
  6254,
  3225,
  2325,
  6110,
  6912,
  7732,
  3283,
  2698,
  220,
  8431,
  2641,
  753,
  5773,
  4122,
  4675,
  5175,
  8465,
  5395,
  5703,
  4297,
  6794,
  5773],
 [714, 4164, 5672, 8124],
 [7674, 4947, 7671, 4335, 1587, 6589, 3669, 6254, 6517],
 [326,
  4211,
  8380,
  7343,
  6084,
  779,
  8542,
  3485,
  5141,
  3078,
  1976,
  4108,
  5922,
  5439,
  4973,
  224,
  4442,
  7792,
  5893],
 [6546, 6949, 1309, 528, 784, 5773],
 [7879, 3385, 230, 7350, 2963, 7473, 5773, 4

In [27]:
voc_size = 10000

In [28]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [29]:
sent_length=30
embedded_docs=pad_sequences(text_new,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 1189 5085 5773]
 [   0    0    0 ... 3647 4413 6700]
 [   0    0    0 ... 1615 7957 5773]
 ...
 [6787 3359 4108 ... 5773 5177 5225]
 [   0    0 6787 ... 3738 2014  154]
 [6787  636 4017 ... 3978 1377 3226]]


In [30]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0, 5573, 1189,
       4017, 1207, 4768, 8542,   17, 1189, 5085, 5773])

In [31]:
embedding_vector_features=30
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(100)))
model1.add(Dropout(0.3))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 30, 30)            300000    
_________________________________________________________________
bidirectional (Bidirectional (None, 200)               104800    
_________________________________________________________________
dropout (Dropout)            (None, 200)               0         
_________________________________________________________________
dense (Dense)                (None, 1)                 201       
Total params: 405,001
Trainable params: 405,001
Non-trainable params: 0
_________________________________________________________________
None


In [32]:
len(embedded_docs),y.shape

(3464, (3464,))

In [33]:
y.value_counts()

0    3348
1     116
Name: category, dtype: int64

In [34]:

import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [35]:
X_final.shape,y_final.shape

((3464, 30), (3464,))

In [36]:
negative = df[df['category']==1]

In [37]:
positive = df[df['category']==0]

In [38]:
print(negative.shape,positive.shape)

(116, 3) (3348, 3)


In [39]:
from imblearn.over_sampling import RandomOverSampler

In [41]:
os = RandomOverSampler()

In [42]:
X_train_res, y_train_res = os.fit_sample(X_final, y_final)

In [43]:
X_train_res.shape,y_train_res.shape

((6696, 30), (6696,))

In [44]:
from collections import Counter
print('Original dataset shape {}'.format(Counter(y_final)))
print('Resampled dataset shape {}'.format(Counter(y_train_res)))

Original dataset shape Counter({0: 3348, 1: 116})
Resampled dataset shape Counter({0: 3348, 1: 3348})


In [45]:
df1 = pd.read_csv('test_.csv')

In [46]:
X = [df1["text"][0]]

In [47]:
X[0].replace("''",'')

'2705 4888 5050 5815 2472 5157 652 2117 2110 325 4462 5931 1177 1911 1177 2084 1177 5094 1177 999 1873 5663 4284 3115 2267 1631 4803 899 5936'

In [48]:
import re

p = re.findall(r'\d+', X[0])

p

['2705',
 '4888',
 '5050',
 '5815',
 '2472',
 '5157',
 '652',
 '2117',
 '2110',
 '325',
 '4462',
 '5931',
 '1177',
 '1911',
 '1177',
 '2084',
 '1177',
 '5094',
 '1177',
 '999',
 '1873',
 '5663',
 '4284',
 '3115',
 '2267',
 '1631',
 '4803',
 '899',
 '5936']

In [49]:
import ast
[ast.literal_eval(i) for i in p]

[2705,
 4888,
 5050,
 5815,
 2472,
 5157,
 652,
 2117,
 2110,
 325,
 4462,
 5931,
 1177,
 1911,
 1177,
 2084,
 1177,
 5094,
 1177,
 999,
 1873,
 5663,
 4284,
 3115,
 2267,
 1631,
 4803,
 899,
 5936]

In [50]:
text1 = []
for i in range(len(df1)):
    text1.append(re.findall(r'\d+',df1["text"][i]))
text1   

[['2705',
  '4888',
  '5050',
  '5815',
  '2472',
  '5157',
  '652',
  '2117',
  '2110',
  '325',
  '4462',
  '5931',
  '1177',
  '1911',
  '1177',
  '2084',
  '1177',
  '5094',
  '1177',
  '999',
  '1873',
  '5663',
  '4284',
  '3115',
  '2267',
  '1631',
  '4803',
  '899',
  '5936'],
 ['389',
  '4978',
  '315',
  '5178',
  '513',
  '5249',
  '5853',
  '3267',
  '315',
  '3891',
  '5465',
  '652',
  '2543',
  '2642',
  '4126',
  '5179',
  '1460',
  '5384',
  '4747',
  '5120',
  '1867',
  '4699',
  '623',
  '4921',
  '5178',
  '1311',
  '1026'],
 ['4478',
  '4231',
  '4858',
  '2638',
  '4231',
  '867',
  '371',
  '686',
  '4888',
  '4179',
  '5886',
  '2272',
  '5097',
  '1409',
  '3239',
  '5631',
  '5178',
  '1809',
  '4757',
  '5587',
  '899',
  '3126',
  '4185',
  '1177',
  '4030',
  '1273',
  '3891',
  '3500',
  '5178',
  '1605'],
 ['3015',
  '1911',
  '112',
  '3905',
  '825',
  '337',
  '315',
  '1693',
  '4677',
  '825',
  '5269',
  '3319',
  '3154',
  '132'],
 ['5136',
  '391

In [51]:
import ast
text_new1 = []
for i in range(len(df1)):
    text_new1.append([ast.literal_eval(j) for j in text1[i]])
text_new1

[[2705,
  4888,
  5050,
  5815,
  2472,
  5157,
  652,
  2117,
  2110,
  325,
  4462,
  5931,
  1177,
  1911,
  1177,
  2084,
  1177,
  5094,
  1177,
  999,
  1873,
  5663,
  4284,
  3115,
  2267,
  1631,
  4803,
  899,
  5936],
 [389,
  4978,
  315,
  5178,
  513,
  5249,
  5853,
  3267,
  315,
  3891,
  5465,
  652,
  2543,
  2642,
  4126,
  5179,
  1460,
  5384,
  4747,
  5120,
  1867,
  4699,
  623,
  4921,
  5178,
  1311,
  1026],
 [4478,
  4231,
  4858,
  2638,
  4231,
  867,
  371,
  686,
  4888,
  4179,
  5886,
  2272,
  5097,
  1409,
  3239,
  5631,
  5178,
  1809,
  4757,
  5587,
  899,
  3126,
  4185,
  1177,
  4030,
  1273,
  3891,
  3500,
  5178,
  1605],
 [3015,
  1911,
  112,
  3905,
  825,
  337,
  315,
  1693,
  4677,
  825,
  5269,
  3319,
  3154,
  132],
 [5136,
  3918,
  5153,
  2023,
  3091,
  4159,
  315,
  3711,
  1409,
  2730,
  1177,
  30,
  2031,
  2730,
  4159,
  2372,
  4865,
  1177],
 [1235,
  3211,
  5420,
  4479,
  2743,
  3707,
  4934,
  2893,
  5600,
  

In [52]:
sent_length=30
embedded_docs1=pad_sequences(text_new1,padding='pre',maxlen=sent_length)
print(embedded_docs1)

[[   0 2705 4888 ... 4803  899 5936]
 [   0    0    0 ... 5178 1311 1026]
 [4478 4231 4858 ... 3500 5178 1605]
 ...
 [3296 4484 4888 ... 5779  888 4888]
 [4304 2283 3747 ... 3204 5262   51]
 [ 497 4677 2543 ... 4937 3204 5120]]


In [53]:
embedded_docs1[0]

array([   0, 2705, 4888, 5050, 5815, 2472, 5157,  652, 2117, 2110,  325,
       4462, 5931, 1177, 1911, 1177, 2084, 1177, 5094, 1177,  999, 1873,
       5663, 4284, 3115, 2267, 1631, 4803,  899, 5936])

In [54]:
import numpy as np
X_test=np.array(embedded_docs1)

In [55]:
X_test.shape

(1360, 30)

In [57]:
y_pred1=model1.predict_classes(X_test)

In [58]:
y_pred1

array([[0],
       [1],
       [0],
       ...,
       [0],
       [1],
       [1]])

In [59]:
df3 = pd.DataFrame(data=y_pred1)
print(df3)

      0
0     0
1     1
2     0
3     1
4     1
5     0
6     0
7     1
8     1
9     0
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    0
18    1
19    1
20    1
21    1
22    1
23    1
24    1
25    1
26    1
27    0
28    0
29    1
30    1
31    1
32    1
33    1
34    1
35    1
36    1
37    1
38    1
39    1
40    1
41    1
42    1
43    1
44    1
45    1
46    1
47    1
48    1
49    1
50    1
51    1
52    1
53    1
54    1
55    0
56    1
57    0
58    0
59    1
60    0
61    0
62    1
63    1
64    1
65    1
66    0
67    1
68    1
69    0
70    0
71    1
72    1
73    0
74    1
75    1
76    0
77    1
78    1
79    1
80    1
81    1
82    1
83    1
84    0
85    0
86    1
87    1
88    1
89    1
90    1
91    1
92    1
93    1
94    0
95    1
96    1
97    1
98    1
99    1
100   1
101   1
102   1
103   1
104   1
105   1
106   1
107   1
108   1
109   1
110   1
111   1
112   1
113   0
114   1
115   0
116   1
117   1
118   1
119   1
120   1
121   1
122   1
123   1


In [47]:
# df3.to_csv("/content/drive/My Drive/Colab Notebooks/SKILLENZA/ML LEVEL 1/df3.csv")

In [48]:
# y_pred1.to_csv

In [60]:
df2 = pd.read_csv("sample_submission_.csv")

In [61]:
df2

id  category
0     3729         1
1     3732         1
2     3761         1
3        5         1
4        7         1
5      228         1
6      236         1
7      241         1
8      251         1
9      260         1
10     265         1
11      19         1
12      21         1
13      22         1
14      23         1
15      24         1
16      25         1
17      26         1
18      27         1
19      28         1
20      29         1
21      30         1
22      31         1
23      32         1
24     759         1
25     772         1
26     774         1
27     776         1
28     780         1
29     783         1
30     791         1
31     796         1
32     800         1
33      44         1
34      45         1
35      46         1
36      47         1
37      48         1
38      49         1
39      50         1
40      51         1
41      52         1
42      53         1
43      54         1
44      56         1
45      58         1
46      59         1
47      60         1
48      61         1
49      62         1
50      63         1
51      64         1
52      65         1
53      67         1
54      70         1
55    2650         1
56    2651         1
57    2655         1
58    2697         1
59    2700         1
60    2705         1
61    2708         1
62    2733         1
63    2752         1
64    2764         1
65    2767         1
66    2773         1
67    2782         1
68    2794         1
69    2796         1
70    2805         1
71    2808         1
72    2815         1
73    2817         1
74    2830         1
75      86         1
76      87         1
77      88         1
78      89         1
79      90         1
80      91         1
81      92         1
82      93         1
83      95         1
84    1034         1
85    1061         1
86    1068         1
87      97         1
88      98         1
89      99         1
90     100         1
91     101         1
92     102         1
93     103         1
94     104         1
95     105         1
96     106         1
97     107         1
98     108         1
99     109         1
100    110         1
101    111         1
102    112         1
103    113         1
104    114         1
105    116         1
106    117         1
107    119         1
108    120         1
109    123         1
110    125         1
111    126         1
112    127         1
113    128         1
114    129         1
115    130         1
116    131         1
117    132         1
118    133         1
119    134         1
120    137         1
121    138         1
122    139         1
123    141         1
124    142         1
125    143         1
126    144         1
127    145         1
128    146         1
129    147         1
130    149         1
131    150         1
132    151         1
133    152         1
134    153         1
135    154         1
136    155         1
137    156         1
138    157         1
139    158         1
140    159         1
141    162         1
142    163         1
143    164         1
144    167         1
145    169         1
146    170         1
147    171         1
148    172         1
149    173         1
150    174         1
151    175         1
152    176         1
153    177         1
154    178         1
155    179         1
156    180         1
157    181         1
158    182         1
159    183         1
160    184         1
161    185         1
162    186         1
163    187         1
164    188         1
165    190         1
166    191         1
167    193         1
168    194         1
169    195         1
170    196         1
171    197         1
172    198         1
173    199         1
174    200         1
175    201         1
176    202         1
177    203         1
178    204         1
179    205         1
180    206         1
181    207         1
182    208         1
183    209         1
184    210         1
185    211         1
186    212         1
187    213         1
188    214         1
189    215        

In [62]:
Y_test = df2['category']

In [63]:
model1.fit(X_train_res,y_train_res,validation_data=(X_test,Y_test),epochs=10,batch_size=64)

Epoch 1/10
105/105 [==============================] - 7s 67ms/step - loss: 0.1572 - accuracy: 0.9249 - val_loss: 5.6842 - val_accuracy: 0.0088
Epoch 2/10
105/105 [==============================] - 6s 61ms/step - loss: 7.7508e-04 - accuracy: 1.0000 - val_loss: 7.0591 - val_accuracy: 0.0059
Epoch 3/10
105/105 [==============================] - 6s 60ms/step - loss: 3.2053e-04 - accuracy: 1.0000 - val_loss: 7.7217 - val_accuracy: 0.0059
Epoch 4/10
105/105 [==============================] - 6s 60ms/step - loss: 1.7066e-04 - accuracy: 1.0000 - val_loss: 8.1676 - val_accuracy: 0.0066
Epoch 5/10
105/105 [==============================] - 6s 59ms/step - loss: 1.1453e-04 - accuracy: 1.0000 - val_loss: 8.4314 - val_accuracy: 0.0066
Epoch 6/10
105/105 [==============================] - 7s 63ms/step - loss: 8.4777e-05 - accuracy: 1.0000 - val_loss: 8.8032 - val_accuracy: 0.0059
Epoch 7/10
105/105 [==============================] - 7s 63ms/step - loss: 6.0470e-05 - accuracy: 1.0000 - val_loss: 9.122

In [64]:
y_pred1 = model1.predict_classes(X_test)

In [65]:
from sklearn.metrics import confusion_matrix

In [66]:
confusion_matrix(Y_test,y_pred1)

array([[   0,    0],
       [1355,    5]], dtype=int64)

In [67]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred1)

0.003676470588235294

In [68]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.00      0.01      1360

    accuracy                           0.00      1360
   macro avg       0.50      0.00      0.00      1360
weighted avg       1.00      0.00      0.01      1360



C:\Users\aakas\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [69]:
sample = pd.read_csv("sample_submission_.csv")
sample

id  category
0     3729         1
1     3732         1
2     3761         1
3        5         1
4        7         1
5      228         1
6      236         1
7      241         1
8      251         1
9      260         1
10     265         1
11      19         1
12      21         1
13      22         1
14      23         1
15      24         1
16      25         1
17      26         1
18      27         1
19      28         1
20      29         1
21      30         1
22      31         1
23      32         1
24     759         1
25     772         1
26     774         1
27     776         1
28     780         1
29     783         1
30     791         1
31     796         1
32     800         1
33      44         1
34      45         1
35      46         1
36      47         1
37      48         1
38      49         1
39      50         1
40      51         1
41      52         1
42      53         1
43      54         1
44      56         1
45      58         1
46      59         1
47      60         1
48      61         1
49      62         1
50      63         1
51      64         1
52      65         1
53      67         1
54      70         1
55    2650         1
56    2651         1
57    2655         1
58    2697         1
59    2700         1
60    2705         1
61    2708         1
62    2733         1
63    2752         1
64    2764         1
65    2767         1
66    2773         1
67    2782         1
68    2794         1
69    2796         1
70    2805         1
71    2808         1
72    2815         1
73    2817         1
74    2830         1
75      86         1
76      87         1
77      88         1
78      89         1
79      90         1
80      91         1
81      92         1
82      93         1
83      95         1
84    1034         1
85    1061         1
86    1068         1
87      97         1
88      98         1
89      99         1
90     100         1
91     101         1
92     102         1
93     103         1
94     104         1
95     105         1
96     106         1
97     107         1
98     108         1
99     109         1
100    110         1
101    111         1
102    112         1
103    113         1
104    114         1
105    116         1
106    117         1
107    119         1
108    120         1
109    123         1
110    125         1
111    126         1
112    127         1
113    128         1
114    129         1
115    130         1
116    131         1
117    132         1
118    133         1
119    134         1
120    137         1
121    138         1
122    139         1
123    141         1
124    142         1
125    143         1
126    144         1
127    145         1
128    146         1
129    147         1
130    149         1
131    150         1
132    151         1
133    152         1
134    153         1
135    154         1
136    155         1
137    156         1
138    157         1
139    158         1
140    159         1
141    162         1
142    163         1
143    164         1
144    167         1
145    169         1
146    170         1
147    171         1
148    172         1
149    173         1
150    174         1
151    175         1
152    176         1
153    177         1
154    178         1
155    179         1
156    180         1
157    181         1
158    182         1
159    183         1
160    184         1
161    185         1
162    186         1
163    187         1
164    188         1
165    190         1
166    191         1
167    193         1
168    194         1
169    195         1
170    196         1
171    197         1
172    198         1
173    199         1
174    200         1
175    201         1
176    202         1
177    203         1
178    204         1
179    205         1
180    206         1
181    207         1
182    208         1
183    209         1
184    210         1
185    211         1
186    212         1
187    213         1
188    214         1
189    215        

In [58]:
##naive bayes

In [70]:
from sklearn.naive_bayes import MultinomialNB
model2 = MultinomialNB()
model2.fit(X_train_res, y_train_res)
model2.predict(X_test)
pd.DataFrame(model2.predict(X_test))
category_naive = sample
category_naive["category"] = pd.DataFrame(model2.predict(X_test))[0]
category_naive["category"].value_counts()

0    713
1    647
Name: category, dtype: int64

In [122]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression()
lg.fit(X_train_res, y_train_res)
lg.predict(X_test)
pd.DataFrame(lg.predict(X_test))
category_lg = sample
category_lg["category"] = pd.DataFrame(lg.predict(X_test))[0]
category_lg["category"].value_counts()

0    770
1    590
Name: category, dtype: int64

In [158]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(X_train_res, y_train_res)
dt.predict(X_test)
pd.DataFrame(dt.predict(X_test))
category_dt = sample
category_dt["category"] = pd.DataFrame(dt.predict(X_test))[0]
category_dt["category"].value_counts()

0    1255
1     105
Name: category, dtype: int64

In [67]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train_res, y_train_res)
rf.predict(X_test)
pd.DataFrame(rf.predict(X_test))
category_rf = sample
category_rf["category"] = pd.DataFrame(rf.predict(X_test))[0]
category_rf["category"].value_counts()

0    1340
1      20
Name: category, dtype: int64

In [142]:
from sklearn.svm import SVC
svm = SVC()
svm.fit(X_train_res, y_train_res)
svm.predict(X_test)
pd.DataFrame(svm.predict(X_test))
category_svm = sample
category_svm["category"] = pd.DataFrame(svm.predict(X_test))[0]
category_svm

id  category
0     3729         0
1     3732         0
2     3761         0
3        5         0
4        7         0
...    ...       ...
1355   311         0
1356   324         0
1357   329         0
1358   342         0
1359   352         0

[1360 rows x 2 columns]

In [143]:
# category_naive.to_csv("D:\\Skillenza_Bootcamp\\ML Level1\\Problem1\\category_naive.csv")
# category_lg.to_csv("D:\\Skillenza_Bootcamp\\ML Level1\\Problem1\\category_lg.csv")
# category_dt.to_csv("D:\\Skillenza_Bootcamp\\ML Level1\\Problem1\\category_dt.csv")
# category_svm.to_csv("D:\\Skillenza_Bootcamp\\ML Level1\\Problem1\\category_svm.csv")

In [72]:
category_naive.to_csv("D:\\Skillenza_Bootcamp\\ML Level1\\Problem1\\category_naive1.csv",index=False)