In [215]:
## Importing Libraries
import numpy as np
import pandas as pd

In [216]:
## Reading Data
df = pd.read_csv('training.csv')
df

id  category                                               text
0      959         0    5573 1189 4017 1207 4768 8542 17 1189 5085 5773
1      994         0       6315 7507 6700 4742 1944 2692 3647 4413 6700
2      995         0                      5015 8067 5335 1615 7957 5773
3      996         0  2925 7199 1994 4647 7455 5773 4518 2734 2807 8...
4      997         0                  7136 1207 6781 237 4971 3669 6193
5      998         0  6730 3349 2325 7714 5773 5172 6254 4097 6500 6...
6      999         0                                 714 4164 5672 8124
7     1000         0       7674 4947 7671 4335 1587 6589 3669 6254 6517
8     1001         0  326 4211 8380 7343 6084 779 8542 3485 5141 307...
9     1002         0                        6546 6949 1309 528 784 5773
10    1003         0  7879 3385 230 7350 2963 7473 5773 4456 941 826...
11    1005         0                           3899 7107 6919 4676 7526
12    1006         0                 2875 7182 4580 2266 3342 1189 3078
13    1007         0  7113 6739 8095 5597 6739 5441 6739 5483 6739 6...
14    1008         0  5598 230 853 5335 3601 2134 1041 5094 1499 577...
15    1009         0  8066 4017 6084 2031 2423 4017 1273 2230 2734 3...
16    1010         0                             1325 8406 163 237 8631
17    1011         0  7152 1253 237 8125 8631 6465 907 5107 3439 647...
18    1012         0  676 349 25 4017 3730 5894 2734 572 3078 4456 6...
19    1013         0  4518 2698 2295 1088 2779 4194 237 2176 1444 27...
20    1014         0  7860 4586 7924 7937 791 1543 5143 6655 7526 58...
21    1015         0     2875 3527 44 2154 5551 3468 3287 8542 1095 572
22    1016         0  5092 3225 8486 5658 6625 1784 3078 7152 3743 7...
23    1017         0                  5270 4184 8542 7444 105 6527 3078
24    1018         0  7408 230 1813 4139 3283 2808 224 2698 7807 393...
25    1019         0  3898 2698 1444 3647 7771 4252 6220 7526 7685 5...
26    1021         0  6591 254 2940 2963 4357 1556 4727 5773 6739 49...
27    1022         0  6084 5063 6349 230 4678 1872 4533 3964 2180 48...
28    1023         0            3866 5773 4442 6169 5922 5620 3485 4017
29    1024         0                 7718 2734 6781 1659 4647 4318 5773
30    1025         0  4138 2734 2230 2573 8207 5773 1908 1519 5045 6...
31    1026         0  6084 2086 1698 1364 6794 3581 8600 5795 4675 3...
32    1027         0  5373 1179 569 237 6013 8155 5658 1179 1493 567...
33    1030         0                                 7312 5215 526 8057
34    1031         0            7627 5457 1755 3668 4912 6193 1651 5239
35    1033         0                   1489 4178 230 1313 3718 727 6700
36    1035         0                  2698 3590 3500 237 7721 1948 5071
37    1036         0  3821 1925 3477 1086 5534 1994 8542 1789 6248 2...
38    1037         0  7018 8380 8406 3924 753 2573 1824 4929 2698 34...
39    1038         0  2977 2457 5694 5672 7605 3208 1556 6265 237 14...
40    1039         0  5096 8155 4032 5579 5071 3123 4144 8573 230 50...
41    1040         0  228 8380 5773 6084 1780 6300 237 5219 6419 366...
42    1041         0            1796 3321 2513 6619 3718 6999 3825 5773
43    1042         0  4138 3718 3626 1462 7642 5658 3385 4017 4041 3...
44    1043         0  590 2242 5773 2698 7027 5395 7924 4408 224 305...
45    1044         0  2297 7526 1273 3468 4608 7171 6953 1942 230 84...
46    1045         0  6084 6170 142 2734 3468 6640 230 8406 6843 307...
47    1046         0                   2297 5551 7920 230 198 4589 6898
48    1047         0  7435 4567 8138 3968 7526 1489 230 2698 2835 67...
49    1048         0                                      590 8380 6700
50    1049         0            6026 1698 7982 1224 6619 4559 8084 3078
51    1050         0  431 12 4017 6084 4799 5922 6024 224 1444 834 2...
52    1051         0                       244 2698 2295 1556 5348 5773
53    1052         0  4878 1698 3092 6619 5071 6343 7526 3746 1309 5...
54    1053         0  3746 468 2734 1656 3078 60

In [217]:
x = [df["text"][0]]

In [218]:
y=df['category']

In [219]:
x[0].replace("''",'')

'5573 1189 4017 1207 4768 8542 17 1189 5085 5773'

In [220]:
import re

s = re.findall(r'\d+', x[0])

s

['5573', '1189', '4017', '1207', '4768', '8542', '17', '1189', '5085', '5773']

In [221]:
import ast
[ast.literal_eval(i) for i in s]

[5573, 1189, 4017, 1207, 4768, 8542, 17, 1189, 5085, 5773]

In [222]:
text = []
for i in range(len(df)):
    text.append(re.findall(r'\d+',df["text"][i]))

In [223]:
import ast
text_new = []
for i in range(len(df)):
    text_new.append([ast.literal_eval(j) for j in text[i]]) 

In [224]:
l = []
for i in range(len(text_new)):
    l.append(len(text_new[i]))   

In [225]:
pd.set_option("display.max_rows",None)
pd.DataFrame(pd.DataFrame(l)[0].value_counts())

0
8     262
7     259
9     224
6     203
10    183
11    176
12    163
5     143
13    127
14    118
15    117
17     90
16     84
18     73
20     71
19     66
22     59
21     58
23     56
30     55
27     52
4      51
32     51
33     51
29     51
25     49
26     48
24     42
28     41
31     41
34     39
38     34
35     31
37     30
36     27
3      27
39     24
2      22
41     20
40     17
44     13
1      13
43     10
45      8
42      6
54      5
101     5
47      5
48      4
46      4
63      3
50      3
55      3
88      3
67      2
74      2
116     2
73      2
86      2
77      2
83      2
87      2
158     2
64      2
72      2
79      1
65      1
75      1
103     1
105     1
69      1
129     1
76      1
49      1
59      1
51      1
110     1
6290    1
52      1
84      1
58      1
60      1
62      1
66      1
68      1
70      1
185     1

In [226]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [227]:
text_new

[[5573, 1189, 4017, 1207, 4768, 8542, 17, 1189, 5085, 5773],
 [6315, 7507, 6700, 4742, 1944, 2692, 3647, 4413, 6700],
 [5015, 8067, 5335, 1615, 7957, 5773],
 [2925,
  7199,
  1994,
  4647,
  7455,
  5773,
  4518,
  2734,
  2807,
  853,
  8542,
  2283,
  753,
  5107,
  5922,
  4355,
  6054,
  4608,
  2199,
  142,
  4211,
  8103,
  5773,
  7747],
 [7136, 1207, 6781, 237, 4971, 3669, 6193],
 [6730,
  3349,
  2325,
  7714,
  5773,
  5172,
  6254,
  4097,
  6500,
  6927,
  5107,
  5045,
  5773,
  3533,
  3255,
  6254,
  3225,
  2325,
  6110,
  6912,
  7732,
  3283,
  2698,
  220,
  8431,
  2641,
  753,
  5773,
  4122,
  4675,
  5175,
  8465,
  5395,
  5703,
  4297,
  6794,
  5773],
 [714, 4164, 5672, 8124],
 [7674, 4947, 7671, 4335, 1587, 6589, 3669, 6254, 6517],
 [326,
  4211,
  8380,
  7343,
  6084,
  779,
  8542,
  3485,
  5141,
  3078,
  1976,
  4108,
  5922,
  5439,
  4973,
  224,
  4442,
  7792,
  5893],
 [6546, 6949, 1309, 528, 784, 5773],
 [7879, 3385, 230, 7350, 2963, 7473, 5773, 4

In [228]:
voc_size = 10000

In [229]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [230]:
sent_length=25
embedded_docs=pad_sequences(text_new,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 1189 5085 5773]
 [   0    0    0 ... 3647 4413 6700]
 [   0    0    0 ... 1615 7957 5773]
 ...
 [4909 5342  224 ... 5773 5177 5225]
 [5573 5979 4457 ... 3738 2014  154]
 [7410 1352 5239 ... 3978 1377 3226]]


In [231]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0, 5573, 1189, 4017, 1207, 4768, 8542,   17,
       1189, 5085, 5773])

In [232]:
embedding_vector_features=25
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(100)))
model1.add(Dropout(0.3))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 25, 25)            250000    
_________________________________________________________________
bidirectional_3 (Bidirection (None, 200)               100800    
_________________________________________________________________
dropout_3 (Dropout)          (None, 200)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 201       
Total params: 351,001
Trainable params: 351,001
Non-trainable params: 0
_________________________________________________________________
None


In [233]:
len(embedded_docs),y.shape

(3464, (3464,))

In [234]:
y.value_counts()

0    3348
1     116
Name: category, dtype: int64

In [235]:

import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [236]:
X_final.shape,y_final.shape

((3464, 25), (3464,))

In [237]:
negative = df[df['category']==1]

In [238]:
positive = df[df['category']==0]

In [239]:
print(negative.shape,positive.shape)

(116, 3) (3348, 3)


In [240]:
from imblearn.over_sampling import RandomOverSampler

In [241]:
os = RandomOverSampler()

In [242]:
X_train, y_train = os.fit_sample(X_final, y_final)

In [243]:
X_train.shape,y_train.shape

((6696, 25), (6696,))

In [244]:
from collections import Counter
print('Original dataset shape {}'.format(Counter(y_final)))
print('Resampled dataset shape {}'.format(Counter(y_train)))

Original dataset shape Counter({0: 3348, 1: 116})
Resampled dataset shape Counter({0: 3348, 1: 3348})


In [245]:
df1 = pd.read_csv('test_.csv')

In [246]:
X = [df1["text"][0]]

In [247]:
X[0].replace("''",'')

'2705 4888 5050 5815 2472 5157 652 2117 2110 325 4462 5931 1177 1911 1177 2084 1177 5094 1177 999 1873 5663 4284 3115 2267 1631 4803 899 5936'

In [248]:
import re

p = re.findall(r'\d+', X[0])

p

['2705',
 '4888',
 '5050',
 '5815',
 '2472',
 '5157',
 '652',
 '2117',
 '2110',
 '325',
 '4462',
 '5931',
 '1177',
 '1911',
 '1177',
 '2084',
 '1177',
 '5094',
 '1177',
 '999',
 '1873',
 '5663',
 '4284',
 '3115',
 '2267',
 '1631',
 '4803',
 '899',
 '5936']

In [249]:
import ast
[ast.literal_eval(i) for i in p]

[2705,
 4888,
 5050,
 5815,
 2472,
 5157,
 652,
 2117,
 2110,
 325,
 4462,
 5931,
 1177,
 1911,
 1177,
 2084,
 1177,
 5094,
 1177,
 999,
 1873,
 5663,
 4284,
 3115,
 2267,
 1631,
 4803,
 899,
 5936]

In [250]:
text1 = []
for i in range(len(df1)):
    text1.append(re.findall(r'\d+',df1["text"][i]))

In [251]:
import ast
text_new1 = []
for i in range(len(df1)):
    text_new1.append([ast.literal_eval(j) for j in text1[i]])

In [252]:
sent_length=25
embedded_docs1=pad_sequences(text_new1,padding='pre',maxlen=sent_length)
print(embedded_docs1)

[[2472 5157  652 ... 4803  899 5936]
 [ 315 5178  513 ... 5178 1311 1026]
 [ 867  371  686 ... 3500 5178 1605]
 ...
 [2956 4677 3606 ... 5779  888 4888]
 [3517 2318 4362 ... 3204 5262   51]
 [5172  175 2462 ... 4937 3204 5120]]


In [253]:
embedded_docs1[0]

array([2472, 5157,  652, 2117, 2110,  325, 4462, 5931, 1177, 1911, 1177,
       2084, 1177, 5094, 1177,  999, 1873, 5663, 4284, 3115, 2267, 1631,
       4803,  899, 5936])

In [254]:
import numpy as np
X_test=np.array(embedded_docs1)

In [255]:
X_test.shape

(1360, 25)

In [256]:
y_pred1=model1.predict_classes(X_test)

In [257]:
y_pred1

array([[1],
       [0],
       [1],
       ...,
       [0],
       [1],
       [1]])

In [258]:
df3 = pd.DataFrame(data=y_pred1)
print(df3)

      0
0     1
1     0
2     1
3     0
4     0
5     0
6     0
7     1
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    1
18    0
19    0
20    0
21    0
22    1
23    0
24    0
25    0
26    1
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    0
39    1
40    0
41    0
42    0
43    1
44    0
45    0
46    0
47    0
48    1
49    0
50    0
51    0
52    1
53    0
54    0
55    1
56    0
57    0
58    0
59    1
60    0
61    1
62    1
63    0
64    0
65    1
66    1
67    1
68    0
69    0
70    1
71    0
72    0
73    0
74    1
75    0
76    1
77    1
78    0
79    0
80    0
81    1
82    1
83    0
84    0
85    0
86    0
87    0
88    0
89    1
90    0
91    0
92    0
93    0
94    1
95    0
96    0
97    0
98    0
99    0
100   0
101   0
102   0
103   0
104   1
105   0
106   1
107   0
108   0
109   0
110   0
111   0
112   0
113   1
114   0
115   0
116   0
117   0
118   0
119   0
120   0
121   0
122   0
123   0


In [259]:
# df3.to_csv("/content/drive/My Drive/Colab Notebooks/SKILLENZA/ML LEVEL 1/df3.csv")

In [260]:
# y_pred1.to_csv

In [261]:
df2 = pd.read_csv("sample_submission_.csv")

In [262]:
df2

id  category
0     3729         1
1     3732         1
2     3761         1
3        5         1
4        7         1
5      228         1
6      236         1
7      241         1
8      251         1
9      260         1
10     265         1
11      19         1
12      21         1
13      22         1
14      23         1
15      24         1
16      25         1
17      26         1
18      27         1
19      28         1
20      29         1
21      30         1
22      31         1
23      32         1
24     759         1
25     772         1
26     774         1
27     776         1
28     780         1
29     783         1
30     791         1
31     796         1
32     800         1
33      44         1
34      45         1
35      46         1
36      47         1
37      48         1
38      49         1
39      50         1
40      51         1
41      52         1
42      53         1
43      54         1
44      56         1
45      58         1
46      59         1
47      60         1
48      61         1
49      62         1
50      63         1
51      64         1
52      65         1
53      67         1
54      70         1
55    2650         1
56    2651         1
57    2655         1
58    2697         1
59    2700         1
60    2705         1
61    2708         1
62    2733         1
63    2752         1
64    2764         1
65    2767         1
66    2773         1
67    2782         1
68    2794         1
69    2796         1
70    2805         1
71    2808         1
72    2815         1
73    2817         1
74    2830         1
75      86         1
76      87         1
77      88         1
78      89         1
79      90         1
80      91         1
81      92         1
82      93         1
83      95         1
84    1034         1
85    1061         1
86    1068         1
87      97         1
88      98         1
89      99         1
90     100         1
91     101         1
92     102         1
93     103         1
94     104         1
95     105         1
96     106         1
97     107         1
98     108         1
99     109         1
100    110         1
101    111         1
102    112         1
103    113         1
104    114         1
105    116         1
106    117         1
107    119         1
108    120         1
109    123         1
110    125         1
111    126         1
112    127         1
113    128         1
114    129         1
115    130         1
116    131         1
117    132         1
118    133         1
119    134         1
120    137         1
121    138         1
122    139         1
123    141         1
124    142         1
125    143         1
126    144         1
127    145         1
128    146         1
129    147         1
130    149         1
131    150         1
132    151         1
133    152         1
134    153         1
135    154         1
136    155         1
137    156         1
138    157         1
139    158         1
140    159         1
141    162         1
142    163         1
143    164         1
144    167         1
145    169         1
146    170         1
147    171         1
148    172         1
149    173         1
150    174         1
151    175         1
152    176         1
153    177         1
154    178         1
155    179         1
156    180         1
157    181         1
158    182         1
159    183         1
160    184         1
161    185         1
162    186         1
163    187         1
164    188         1
165    190         1
166    191         1
167    193         1
168    194         1
169    195         1
170    196         1
171    197         1
172    198         1
173    199         1
174    200         1
175    201         1
176    202         1
177    203         1
178    204         1
179    205         1
180    206         1
181    207         1
182    208         1
183    209         1
184    210         1
185    211         1
186    212         1
187    213         1
188    214         1
189    215        

In [263]:
Y_test = df2['category']

In [264]:
model1.fit(X_train,y_train,validation_data=(X_test,Y_test),epochs=10,batch_size=64)

Epoch 1/10
105/105 [==============================] - 5s 51ms/step - loss: 0.1340 - accuracy: 0.9534 - val_loss: 5.4145 - val_accuracy: 0.0044
Epoch 2/10
105/105 [==============================] - 5s 45ms/step - loss: 0.0019 - accuracy: 0.9999 - val_loss: 6.5252 - val_accuracy: 0.0000e+00
Epoch 3/10
105/105 [==============================] - 4s 39ms/step - loss: 4.3186e-04 - accuracy: 1.0000 - val_loss: 7.9039 - val_accuracy: 0.0000e+00
Epoch 4/10
105/105 [==============================] - 4s 39ms/step - loss: 1.9110e-04 - accuracy: 1.0000 - val_loss: 8.5490 - val_accuracy: 0.0000e+00
Epoch 5/10
105/105 [==============================] - 4s 42ms/step - loss: 1.1676e-04 - accuracy: 1.0000 - val_loss: 8.9916 - val_accuracy: 0.0000e+00
Epoch 6/10
105/105 [==============================] - 4s 40ms/step - loss: 8.0523e-05 - accuracy: 1.0000 - val_loss: 9.3259 - val_accuracy: 0.0000e+00
Epoch 7/10
105/105 [==============================] - 5s 45ms/step - loss: 5.5722e-05 - accuracy: 1.0000 -

In [265]:
y_pred1 = model1.predict_classes(X_test)

In [266]:
from sklearn.metrics import confusion_matrix

In [267]:
confusion_matrix(Y_test,y_pred1)

array([[   0,    0],
       [1360,    0]], dtype=int64)

In [268]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred1)

0.0

In [269]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       0.0
           1       0.00      0.00      0.00    1360.0

    accuracy                           0.00    1360.0
   macro avg       0.00      0.00      0.00    1360.0
weighted avg       0.00      0.00      0.00    1360.0



C:\Users\aakas\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\aakas\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [270]:
sample = pd.read_csv("sample_submission_.csv")
sample

id  category
0     3729         1
1     3732         1
2     3761         1
3        5         1
4        7         1
5      228         1
6      236         1
7      241         1
8      251         1
9      260         1
10     265         1
11      19         1
12      21         1
13      22         1
14      23         1
15      24         1
16      25         1
17      26         1
18      27         1
19      28         1
20      29         1
21      30         1
22      31         1
23      32         1
24     759         1
25     772         1
26     774         1
27     776         1
28     780         1
29     783         1
30     791         1
31     796         1
32     800         1
33      44         1
34      45         1
35      46         1
36      47         1
37      48         1
38      49         1
39      50         1
40      51         1
41      52         1
42      53         1
43      54         1
44      56         1
45      58         1
46      59         1
47      60         1
48      61         1
49      62         1
50      63         1
51      64         1
52      65         1
53      67         1
54      70         1
55    2650         1
56    2651         1
57    2655         1
58    2697         1
59    2700         1
60    2705         1
61    2708         1
62    2733         1
63    2752         1
64    2764         1
65    2767         1
66    2773         1
67    2782         1
68    2794         1
69    2796         1
70    2805         1
71    2808         1
72    2815         1
73    2817         1
74    2830         1
75      86         1
76      87         1
77      88         1
78      89         1
79      90         1
80      91         1
81      92         1
82      93         1
83      95         1
84    1034         1
85    1061         1
86    1068         1
87      97         1
88      98         1
89      99         1
90     100         1
91     101         1
92     102         1
93     103         1
94     104         1
95     105         1
96     106         1
97     107         1
98     108         1
99     109         1
100    110         1
101    111         1
102    112         1
103    113         1
104    114         1
105    116         1
106    117         1
107    119         1
108    120         1
109    123         1
110    125         1
111    126         1
112    127         1
113    128         1
114    129         1
115    130         1
116    131         1
117    132         1
118    133         1
119    134         1
120    137         1
121    138         1
122    139         1
123    141         1
124    142         1
125    143         1
126    144         1
127    145         1
128    146         1
129    147         1
130    149         1
131    150         1
132    151         1
133    152         1
134    153         1
135    154         1
136    155         1
137    156         1
138    157         1
139    158         1
140    159         1
141    162         1
142    163         1
143    164         1
144    167         1
145    169         1
146    170         1
147    171         1
148    172         1
149    173         1
150    174         1
151    175         1
152    176         1
153    177         1
154    178         1
155    179         1
156    180         1
157    181         1
158    182         1
159    183         1
160    184         1
161    185         1
162    186         1
163    187         1
164    188         1
165    190         1
166    191         1
167    193         1
168    194         1
169    195         1
170    196         1
171    197         1
172    198         1
173    199         1
174    200         1
175    201         1
176    202         1
177    203         1
178    204         1
179    205         1
180    206         1
181    207         1
182    208         1
183    209         1
184    210         1
185    211         1
186    212         1
187    213         1
188    214         1
189    215        

In [271]:
##naive bayes

In [272]:
from sklearn.naive_bayes import MultinomialNB
model2 = MultinomialNB()
model2.fit(X_train, y_train)
model2.predict(X_test)
pd.DataFrame(model2.predict(X_test))
category_naive = sample
category_naive["category"] = pd.DataFrame(model2.predict(X_test))[0]
category_naive["category"].value_counts()

1    700
0    660
Name: category, dtype: int64

In [280]:
# category_naive.to_csv("D:\\Skillenza_Bootcamp\\ML Level1\\Problem1\\category_naive5.csv",index=False)

In [274]:
# from sklearn.linear_model import LogisticRegression
# lg = LogisticRegression()
# lg.fit(X_train, y_train)
# lg.predict(X_test)
# pd.DataFrame(lg.predict(X_test))
# category_lg = sample
# category_lg["category"] = pd.DataFrame(lg.predict(X_test))[0]
# category_lg["category"].value_counts()

In [275]:
# from sklearn.tree import DecisionTreeClassifier
# dt = DecisionTreeClassifier()
# dt.fit(X_train, y_train)
# dt.predict(X_test)
# pd.DataFrame(dt.predict(X_test))
# category_dt = sample
# category_dt["category"] = pd.DataFrame(dt.predict(X_test))[0]
# category_dt["category"].value_counts()

In [276]:
# from sklearn.ensemble import RandomForestClassifier
# rf = RandomForestClassifier()
# rf.fit(X_train, y_train)
# rf.predict(X_test)
# pd.DataFrame(rf.predict(X_test))
# category_rf = sample
# category_rf["category"] = pd.DataFrame(rf.predict(X_test))[0]
# category_rf["category"].value_counts()

In [277]:
# from sklearn.svm import SVC
# svm = SVC()
# svm.fit(X_train, y_train)
# svm.predict(X_test)
# pd.DataFrame(svm.predict(X_test))
# category_svm = sample
# category_svm["category"] = pd.DataFrame(svm.predict(X_test))[0]
# category_svm

In [278]:
# category_naive.to_csv("D:\\Skillenza_Bootcamp\\ML Level1\\Problem1\\category_naive.csv")
# category_lg.to_csv("D:\\Skillenza_Bootcamp\\ML Level1\\Problem1\\category_lg.csv")
# category_dt.to_csv("D:\\Skillenza_Bootcamp\\ML Level1\\Problem1\\category_dt.csv")
# category_svm.to_csv("D:\\Skillenza_Bootcamp\\ML Level1\\Problem1\\category_svm.csv")

In [279]:
# category_naive.to_csv("D:\\Skillenza_Bootcamp\\ML Level1\\Problem1\\category_naive2.csv",index=False)