In [37]:
n = list(map(int,input("Enter Integer and No of Queries : ").split()))
print(n)

Enter Integer and No of Queries : 3 1
[3, 1]


In [38]:
x = list(map(int,input("Enter Sequence : ").split()[:2**n[0]]))
print(x)

Enter Sequence : 1 2 3 4 5 6 7 8
[1, 2, 3, 4, 5, 6, 7, 8]


In [56]:
np.bitwise_or(a1[1][0],a1[1][1])

7

In [31]:
# Que = []
# for i in range(n[1]):
#     Que.append(list(map(int,input("Enter Queries : ").split())))

In [39]:
a1 = np.array(x)
a1.resize((int(len(x)/2),2))
a1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [40]:
Or = []
for i in range(len(a1)):
    Or.append(a1[i][0] | a1[i][1] )
Or        

[3, 7, 7, 15]

In [41]:
a2 = np.array(Or)
a2.resize((int(len(x)/4),2))
a2

array([[ 3,  7],
       [ 7, 15]])

In [ ]:
for i in range(len(Que)):
    SegmentTree(x).update(Que[i][0]-1,Que[i][1])
    a1 = np.array(x)
    a1.resize((int(len(x)/2),2))
    Or = []
    for i in range(len(a1)):
        Or.append(a1[i][0] | a1[i][1] )
    a2 = np.array(Or)
    a2.resize((int(len(x)/4),2))
    print(a2[i][0] ^ a2[i][1] )

In [26]:
a1 = np.array(x)
a1.resize((int(len(a1)/2),2))
a1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [46]:
np.bitwise_or(x[2],x[3])

7

In [11]:
Or = []
for i in range(len(a1)):
    Or.append(a1[i][0] | a1[i][1] )
Or

[3, 7, 7, 15]

In [ ]:
a2 = np.array()
a2.resize((int(len(x)/4),2))
print(a2[0][0] ^ a2[0][1] )

In [114]:
6^7

1

In [21]:
lst = []
for i in range(0,n[1]):
    ele = list(map(int,input("Enter Queries : ").split()))
    lst.append(ele)
print(lst)

Enter Queries : 2 4
Enter Queries : 1 2
Enter Queries : 2 5
Enter Queries : 1 7
[[2, 4], [1, 2], [2, 5], [1, 7]]


In [200]:
# from segment_tree import SegmentTree
# n = list(map(int,input("Enter Integer and No of Queries : ").split()))
# x = list(map(int,input("Enter Sequence : ").split()[:2**n[0]]))
# Que = []
# for i in range(n[1]):
#     Que.append(list(map(int,input("Enter Queries : ").split())))
# import numpy as np
# a1 = np.array(x)
# a1.resize((int(len(x)/2),2))
# a1
# Or = []
# for i in range(len(a1)):
#     Or.append(a1[i][0] | a1[i][1] )
# a2 = np.array(Or)
# a2.resize((int(len(x)/4),2))
# a2 
# print(a2[0][0] ^ a2[0][1] )

Enter Integer and No of Queries : 2 4
Enter Sequence : 1 6 3 5
Enter Queries : 1 4
Enter Queries : 3 4
Enter Queries : 1 2
Enter Queries : 1 2
0


In [12]:
# from segment_tree import SegmentTree
# import numpy as np
# n = list(map(int,input("Enter Integer and No of Queries : ").split()))
# x = list(map(int,input("Enter Sequence : ").split()[:2**n[0]]))
# Que = []
# for i in range(n[1]):
#     Que.append(list(map(int,input("Enter Queries : ").split())))
# for i in range(len(Que)):
#     SegmentTree(x).update(Que[i][0]-1,Que[i][1])
#     a1 = np.array(x)
#     a1.resize((int(len(x)/2),2))
#     Or = []
#     for i in range(len(a1)):
#         Or.append(a1[i][0] | a1[i][1] )
#     a2 = np.array(Or)
#     a2.resize((int(len(x)/4),2))
#     print(a2[0][0] ^ a2[0][1] )

Enter Integer and No of Queries : 4 1
Enter Sequence : 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
Enter Queries : 1 0
5


In [ ]:
4 elements  2 arrays() 

In [13]:
from segment_tree import SegmentTree
import numpy as np
n = list(map(int,input("Enter Integer and No of Queries : ").split()))
x = list(map(int,input("Enter Sequence : ").split()[:2**n[0]]))
Que = []
for i in range(n[1]):
    Que.append(list(map(int,input("Enter Queries : ").split())))
for i in range(len(Que)):
    SegmentTree(x).update(Que[i][0]-1,Que[i][1])
    a1 = np.array(x)
    a1.resize((int(len(x)/2),2))
    Or = []
    for i in range(len(a1)):
        Or.append(a1[i][0] | a1[i][1] )
    a2 = np.array(Or)
    a2.resize((int(len(x)/4),2))
    print(a2[i][0] ^ a2[i][1] )

Enter Integer and No of Queries : 4 1
Enter Sequence : 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
Enter Queries : 1 0


IndexError: index 7 is out of bounds for axis 0 with size 4

In [15]:
x

[0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

In [216]:
# from segment_tree import SegmentTree
# import numpy as np
# n = list(map(int,input().split()))
# x = list(map(int,input().split()[:2**n[0]]))
# Que = []
# for i in range(n[1]):
#     Que.append(list(map(int,input().split())))
# for i in range(len(Que)):
#     SegmentTree(x).update(Que[i][0]-1,Que[i][1])
#     a1 = np.array(x)
#     a1.resize((int(len(x)/2),2))
#     Or = []
#     for i in range(len(a1)):
#         Or.append(a1[i][0] | a1[i][1] )
#     a2 = np.array(Or)
#     a2.resize((int(len(x)/4),2))
#     for i in range(len(a2)):
#         print(a2[i][0] ^ a2[i][1] )

3 6
1 5 8 9 7 6 3 4
1 6
2 9
4 7
3 2
2 4
5 3
14
0
6
0
0
0
8
0
1
0
1
0


In [220]:
a2[]

2

In [214]:
a2[0][2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [204]:
# for i in range(len(Que)):
#     SegmentTree(x1).update(Que[i][0]-1,Que[i][1])
#     print(x1)

In [205]:
# x1 = x.copy()
# x1

In [202]:
Que[0]

[1, 4]

In [180]:
SegmentTree(x1).update(1-1,4)
x1

[4, 6, 3, 5]

In [181]:
SegmentTree(x1).update(3-1,4)
x1

[4, 6, 4, 5]

In [182]:
SegmentTree(x1).update(1-1,2)
x1

[2, 6, 4, 5]

In [183]:
SegmentTree(x1).update(1-1,2)
x1

[2, 6, 4, 5]

In [184]:
x

[1, 6, 3, 5]