# Introduction to Numpy package

In [1]:
import numpy as np

In [2]:
data1=[[1,2,3,4],[5,6,7,8]]
myArray= np.array(data1)
print('myArray=',myArray)

print('cumprod =',myArray.cumprod())
myArray.mean()
myArray.shape
#data2=[[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]]

myArray= [[1 2 3 4]
 [5 6 7 8]]
cumprod = [    1     2     6    24   120   720  5040 40320]


(2, 4)

In [3]:
#A=np.zeros(2,5)
? np.zeros

In [4]:
np.zeros([2,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [28]:
myArray[1,1:]

array([6, 7, 8])

In [30]:
# All elments in 2nd column of myArray
myArray[:,1]

array([2, 6])

In [31]:
np.sqrt(myArray)

array([[ 1.        ,  1.41421356,  1.73205081,  2.        ],
       [ 2.23606798,  2.44948974,  2.64575131,  2.82842712]])

np.exp(myArray)

In [33]:
myArray.std()

2.2912878474779199

In [35]:
np.random.random((5,2))

array([[ 0.96607661,  0.9692827 ],
       [ 0.03526467,  0.57981982],
       [ 0.25724589,  0.79196187],
       [ 0.19729027,  0.08190327],
       [ 0.46731878,  0.18746565]])

In [ ]:
myArray2=myArray*2
myArray2

In [39]:
np.append(myArray,myArray2,axis=1)

array([[ 1,  2,  3,  4,  2,  4,  6,  8],
       [ 5,  6,  7,  8, 10, 12, 14, 16]])

In [41]:
np.append(myArray,myArray2,axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 2,  4,  6,  8],
       [10, 12, 14, 16]])