In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

C:\Users\aakas\Anaconda\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\aakas\Anaconda\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
df = pd.read_csv('linearstatmodeldata.csv')

In [3]:
df.head(3)

Unnamed: 0  Year  Month  Interest_Rate  Unemployment_Rate  \
0           0  2017     12           2.75                5.3   
1           1  2017     11           2.50                5.3   
2           2  2017     10           2.50                5.3   

   Stock_Index_Price  
0               1464  
1               1394  
2               1357

In [4]:
X = df[['Interest_Rate','Unemployment_Rate']] # here we have 2 variables for the multiple linear regression. If you just want to use one variable for simple linear regression, then use X = df['Interest_Rate'] for example
Y = df['Stock_Index_Price']

In [5]:
from sklearn import linear_model
reg = linear_model.LinearRegression()

In [6]:
reg

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [8]:
reg.fit(df[['Interest_Rate','Unemployment_Rate']],df.Stock_Index_Price )

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [9]:
reg.coef_

array([ 345.54008701, -250.14657137])

In [11]:
df.head()

Unnamed: 0  Year  Month  Interest_Rate  Unemployment_Rate  \
0           0  2017     12           2.75                5.3   
1           1  2017     11           2.50                5.3   
2           2  2017     10           2.50                5.3   
3           3  2017      9           2.50                5.3   
4           4  2017      8           2.50                5.4   

   Stock_Index_Price  
0               1464  
1               1394  
2               1357  
3               1293  
4               1256

In [13]:
reg.predict([[5.25,5.3]])

array([2286.71260617])

In [14]:
reg.predict([[4.75,5.1]])

array([2163.97187694])