In [7]:
import numpy as np
import sys

In [8]:
# Memory Size of List
a = [1,2,3,4,5,6,7,8,9,10]
sys.getsizeof(a)


144

In [18]:
# Memory Size of Array
seqa = [1,2,3,4]
seqb = [4,5,6,5]
seqc = [7,8,9,9]
seqd = [10,11,12,13]

In [19]:
arrabcd = np.array([seqa,seqb,seqc,seqd])

In [20]:
arrabcd

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  5],
       [ 7,  8,  9,  9],
       [10, 11, 12, 13]])

In [21]:
arrabcd.ndim

2

In [22]:
arrabcd.shape

(4, 4)

In [23]:
arrabcd.size

16

In [24]:
arrabcd.itemsize

4

In [25]:
sys.getsizeof(arrabcd)

176

In [33]:
# Memory Size of Array
seqa = [1,2,3,4]
seqb = [4,5,6,5]
seqc = [7,8,9,9]
seqd = [10,11,12,13]
arrabcd = np.array([seqa,seqb,seqc,seqd])
print(" Dimension :",arrabcd.ndim,"\n","Shape :",arrabcd.shape,"\n","Size :",arrabcd.size,"\n","ItemSize:", arrabcd.itemsize)
print(" Size of a :" + str(arrabcd.size * arrabcd.itemsize))


 Dimension : 2 
 Shape : (4, 4) 
 Size : 16 
 ItemSize: 4
 Size of a :64


In [ ]:
print("Size of a :" + str(arrabcd.size * arrabcd.itemsize))

In [34]:
a.__sizeof__()

120

# RESHAPING

In [36]:
X = np.arange(6)

In [37]:
X

array([0, 1, 2, 3, 4, 5])

In [38]:
X.ndim

1

In [39]:
array2d = X.reshape(3,2)

In [40]:
array2d

array([[0, 1],
       [2, 3],
       [4, 5]])

In [41]:
array2d = X.reshape(2,3)
array2d


array([[0, 1, 2],
       [3, 4, 5]])

In [43]:
arrabcd.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  5],
       [ 7,  8,  9,  9],
       [10, 11, 12, 13]])

# RESHAPING ID DATA INTO 3D DATA

In [45]:
a1d = np.arange(24)
a1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [47]:
a3d = a1d.reshape(3,2,4)
a3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [49]:
a3d1 = a1d.reshape(2,2,6)
a3d1
array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

# SLICING AND INDEXING

In [51]:
seqa = [1,2,3,4]
seqb = [4,5,6,5]
seqc = [7,8,9,9]
seqd = [10,11,12,13]
A = np.array([seqa,seqb,seqc,seqd])
A

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  5],
       [ 7,  8,  9,  9],
       [10, 11, 12, 13]])

In [52]:
A[0]

array([1, 2, 3, 4])

In [53]:
A[0:4]

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  5],
       [ 7,  8,  9,  9],
       [10, 11, 12, 13]])

In [58]:
A[1:,:]

array([], shape=(0, 4), dtype=int32)

In [60]:
A[:,0:3]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [63]:
A[::2,::2]

array([[1, 3],
       [7, 9]])

# NUMPY DATA TYPE

In [77]:
a = np.array([[1,2,3],[4,5,6]])
print("Size :" ,a.size)
print("ItemSize :" ,a.itemsize )
print("Shape :",a.shape)
print("Memory :",a.size * a.itemsize  )
print("Type :",type(a))

Size : 6
ItemSize : 4
Shape : (2, 3)
Memory : 24
Type : <class 'numpy.ndarray'>


In [79]:
a = np.array([[1,2,3],[4,5,6]])
a1 = a.astype(np.int32)
print("Size :" ,a1.size)
print("ItemSize :" ,a1.itemsize )
print("Shape :",a1.shape)
print("Memory :",a1.size * a1.itemsize  )
print("Type :",type(a1))

Size : 6
ItemSize : 4
Shape : (2, 3)
Memory : 24
Type : <class 'numpy.ndarray'>


In [83]:
## Create Array
ar = np.ones((4,4))
ar


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [87]:
ar.dtype

dtype('float64')

In [96]:
Z =  np.full((3,3),8)
print("Z :",Z,"\n")
Z1 = np.random.random((3,4))
print("Z1",Z1)

Z : [[8 8 8]
 [8 8 8]
 [8 8 8]] 

Z1 [[0.69899683 0.75082413 0.87285655 0.1049046 ]
 [0.82288343 0.12774379 0.58626437 0.32573152]
 [0.61967112 0.50061866 0.62642385 0.42403762]]


In [116]:
from random import random
random()


0.13436424411240122

In [113]:
from numpy.random import rand
from random import seed
seed(1)
rand((10))



array([0.67821913, 0.54757133, 0.63583208, 0.95466873, 0.82855752,
       0.0287964 , 0.88424241, 0.3988796 , 0.10688543, 0.74960323])

# MATHS IN NUMPY

In [118]:
b = np.array([[1,2,3],[4,5,6],[6,7,8]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [125]:
print("Sum :",b.sum())
## Rows
print("Axes Row Sum :",b.sum(axis = 1))
## Columns
print("Axes Columns Sum :",b.sum(axis = 0))

##Max
print("Axes Row Max :",b.max(axis = 1))
print("Axes Column Max :",b.max(axis =0))

Sum : 42
Axes Row Sum : [ 6 15 21]
Axes Columns Sum : [11 14 17]
Axes Row Max : [3 6 8]
Axes Column Max : [6 7 8]
