In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.18.1


In [3]:
!pip install numpy

In [ ]:
# Numpy Array is Homogenous
# List can contain int,float,str


In [4]:
a = [1,2,3,4,5,6]

In [5]:
type(a)

list

In [6]:
a = np.array(a)

In [7]:
type(a)

numpy.ndarray

In [8]:
a.ndim

1

In [9]:
a.shape

(6,)

In [10]:
mylist = [10,11,12,13,14,15]

In [11]:
mylist = np.array(mylist)

In [12]:
type(mylist)

numpy.ndarray

In [13]:
mylist.ndim

1

In [14]:
mylist.shape

(6,)

In [17]:
mylist = [10,11,12,13,14,15]
mylist = np.array(mylist)
print(type(mylist),
mylist.ndim,
mylist.shape)

<class 'numpy.ndarray'> 1 (6,)


In [18]:
b = [1,2,3,4,5,"aakash"]
b

[1, 2, 3, 4, 5, 'aakash']

In [19]:
b = np.array(b)

In [20]:
b
# Never add mixed data

array(['1', '2', '3', '4', '5', 'aakash'], dtype='<U11')

In [26]:
array_a = [[1,2,3,4,5],[6,7,8,9,10]]
array_a = np.array(array_a)
array_a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
array_a.shape

(2, 5)

In [33]:
array_b = np.array([[1,2,3],[4,5,6]])
print(array_b.shape,
array_b.ndim)

(2, 3) 2


# CONVERT ARRAY TO LIST

In [34]:
array_b = array_b.tolist()
array_b

[[1, 2, 3], [4, 5, 6]]

In [36]:
seq_a = [1,2,3,4]
seq_b = [4,5,6,7]
seq_c = [7,8,9,10]
array_seq = np.array([seq_a,seq_b,seq_c])
print(array_seq.shape,array_seq.ndim)

(3, 4) 2


# RESHAPING

In [40]:
newarr = np.array([[1,2,3],[4,5,6]])
newarr

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
newarr.shape

(2, 3)

In [42]:
newarr1 = newarr.reshape(3,2)
newarr1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
newarr1.ndim

2

In [48]:
newlist = [[1,2,3,4],[5,6,7,8]]
newarr = np.array([[1,2,3,4],[4,5,6,7]])
newarr.shape
newarr1 = newarr.reshape(4,2)
newarr1

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

# HOW TO KNOW MEMORY SIZE OF OBJECT

In [47]:
print("%d bytes" % (newarr1.size * newarr1.itemsize))

32 bytes


In [70]:
from sys import getsizeof
print(" List_Size :",sys.getsizeof(newlist),"\n","Array_Size :",sys.getsizeof(newarr1))

 List_Size : 80 
 Array_Size : 112


In [55]:
newarr1.nbytes

32

In [62]:
!pip install pympler

  Created wheel for pympler: filename=Pympler-0.8-py3-none-any.whl size=164719 sha256=5b5e4a200cf98581e91d6ef60fac8c58dc46bdba4298b6a375ddaaebb8a09172
  Stored in directory: c:\users\aakas\appdata\local\pip\cache\wheels\a0\a9\99\337816ce8e8acc5b1849abe49c8f637a9be9a5005f72318ecf
Successfully built pympler


In [77]:
# from pympler import asizeof
# asizeof.asizeof(newlist)

In [76]:
#  Difference between nbytes and gestsizeof
# This is because nbytes only returns the size of stored data, 
# while sys.getsizeof returns the size of the whole object, 
# i.e. the size of the stored data plus some overhead. 
# There is a small overhead for numpy arrays, 
# because they have to store the array dimensions, the datatype and similar information.
    
import sys
import numpy as np
x = np.random.rand(10000, 50)
print('newarr1.nbytes: {0} bytes'.format(newarr1.nbytes))
print('newarr1.getsizeof(x): {0} bytes'.format(sys.getsizeof(newarr1)))

newarr1.nbytes: 32 bytes
newarr1.getsizeof(x): 112 bytes


In [78]:
import sys
import numpy as np
x = np.random.rand(10000, 50)
print('x.nbytes: {0} bytes'.format(x.nbytes))
print('sys.getsizeof(x): {0} bytes'.format(sys.getsizeof(x)))

x.nbytes: 4000000 bytes
sys.getsizeof(x): 4000112 bytes


In [84]:
import sys
import numpy as np
x = np.random.rand(10000, 50)
print('newlist.nbytes: {0} bytes'.format(np.asarray(newlist).nbytes))
print('newlist.getsizeof(x): {0} bytes'.format(sys.getsizeof(np.asarray(newlist))))

newlist.nbytes: 32 bytes
newlist.getsizeof(x): 144 bytes


In [104]:
Z = np.arange(50)
Z
# Z = Z[::-1]
# print(Z)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [106]:
Z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [152]:
Z1 = np.arange(50).reshape(10,5)
Z1
Z1[::-1,::-1].reshape(1,50)


144

In [108]:
X = np.arange(100).reshape(10,10)
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [117]:
X1 = X[2:9,3:8]
X1

array([[23, 24, 25, 26, 27],
       [33, 34, 35, 36, 37],
       [43, 44, 45, 46, 47],
       [53, 54, 55, 56, 57],
       [63, 64, 65, 66, 67],
       [73, 74, 75, 76, 77],
       [83, 84, 85, 86, 87]])

In [135]:
X1[::3,::2]

array([[23, 25, 27],
       [53, 55, 57],
       [83, 85, 87]])

In [159]:
X = np.arange(100).reshape(10,10)
X1 = X[2:9,3:8]
X2 = X1[::3,::2]
print("X :",X,"\n","\n","X1 :",X1,"\n","\n","X2 :",X2)

X : [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]] 
 
 X1 : [[23 24 25 26 27]
 [33 34 35 36 37]
 [43 44 45 46 47]
 [53 54 55 56 57]
 [63 64 65 66 67]
 [73 74 75 76 77]
 [83 84 85 86 87]] 
 
 X2 : [[23 25 27]
 [53 55 57]
 [83 85 87]]
