In [1]:
import array as arr

In [2]:
x = arr.array("i",[1,2,3])

In [3]:
def add():
    a=10
    b=20
    c=a+b
    print("Sum:",c)

In [4]:
add()

Sum: 30


In [5]:
class Employee:
    def __init__(self,name,age,salary):
        self.name= name
        self.age=age
        self.salary=salary
E1=Employee("Aakash",22,30000)
print(E1.name)
print(E1.age)
print(E1.salary)

Aakash
22
30000


In [6]:
a = lambda x,y:x+y
a(5,6)

11

In [7]:
from random import shuffle
x = [1,2,3,4,5,6,7,8,9,10]
shuffle(x)
x

[9, 3, 6, 1, 8, 7, 4, 2, 5, 10]

In [8]:
import random
random.randint(1,100)

89

In [9]:
string = "aaKash"
print(string.capitalize(),
string.lower(),
string.upper(),)

Aakash aakash AAKASH


In [10]:
"aakash" in "hi how are you"

False

In [11]:
# List
lst = [1,2]
# tuple
tpe = (1,2)
# Dictionary
dictn = {"Name":"Aakash","Age":"22"}

In [12]:
print(lst,tpe,dictn)

[1, 2] (1, 2) {'Name': 'Aakash', 'Age': '22'}


In [13]:
import re

In [14]:
re.split(r'\s',"My Name is Aakash Nadupalli")

['My', 'Name', 'is', 'Aakash', 'Nadupalli']

In [15]:
re.sub(r'\d+',"*********","Password 123456789")

'Password *********'

In [16]:
re.subn("456","***","Password 123456789 234567 34567 4567 3456789")

('Password 123***789 23***7 3***7 ***7 3***789', 5)

In [17]:
import array as ar
ar1 = ar.array("d",[1.1,1.2])
ar1

array('d', [1.1, 1.2])

In [18]:
ar1.append(1.3)
ar1.extend([1.4,1.5,1.6])
ar1

array('d', [1.1, 1.2, 1.3, 1.4, 1.5, 1.6])

In [19]:
ar1.pop()
ar1

array('d', [1.1, 1.2, 1.3, 1.4, 1.5])

In [20]:
import numpy as np

In [21]:
num1 = [1,2,3]
arr1 = np.array(num1)
num2 = [[1,2,3],[4,5,6]]
arr2 = np.array(num2)
num3 = [[1,2,3],[4,5,6],[7,8,9]]
arr3 = np.array(num3)
print("One-Dimensional-Array :",arr1,arr1.shape,"\n")
print("Two-Dimensional-Array :",arr2,arr2.shape,"\n")
print("Three-Dimensional-Array :",arr3,arr3.shape,"\n")

One-Dimensional-Array : [1 2 3] (3,) 

Two-Dimensional-Array : [[1 2 3]
 [4 5 6]] (2, 3) 

Three-Dimensional-Array : [[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) 



In [22]:
print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [23]:
print(arr1.dtype,arr2.dtype,arr3.dtype)

int32 int32 int32


In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [27]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [28]:
np.random.randint(1,15,4)

array([ 8, 10,  2,  7])

In [29]:
np.random.randint(1,100,20)

array([68, 24, 57, 82, 24, 93, 74, 40, 37, 96, 34, 41,  3, 20, 82, 77, 84,
        2, 69, 27])

In [30]:
np.random.randint([2,3])

array([1, 0])

In [31]:
np.random.seed(123)
np.random.randint(1,100,20)

array([67, 93, 99, 18, 84, 58, 87, 98, 97, 48, 74, 33, 47, 97, 26, 84, 79,
       37, 97, 81])

In [32]:
num = np.array([10,11,12,13])

In [33]:
print(num[1],num[-1],num[2:4])

11 13 [12 13]


In [34]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
np.arange(0,4).reshape(2,2)

array([[0, 1],
       [2, 3]])

In [36]:
np.random.rand()

0.7379954057320357

In [37]:
np.random.rand(25)

array([0.18249173, 0.17545176, 0.53155137, 0.53182759, 0.63440096,
       0.84943179, 0.72445532, 0.61102351, 0.72244338, 0.32295891,
       0.36178866, 0.22826323, 0.29371405, 0.63097612, 0.09210494,
       0.43370117, 0.43086276, 0.4936851 , 0.42583029, 0.31226122,
       0.42635131, 0.89338916, 0.94416002, 0.50183668, 0.62395295])

In [38]:
np.arange(1,101).reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [39]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [40]:
np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [41]:
np.array(np.random.randint(1,50,10)).reshape(2,5)

array([[17,  7, 15, 40, 12],
       [ 8,  2, 44, 38, 26]])

In [42]:
np.arange(1,10).tolist()

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [43]:
np.array([1,10,15,24,26])[np.array([1,10,15,24,26])>10]

array([15, 24, 26])

In [44]:
np.array([2,4,5,6,8,10])[np.array([2,4,5,6,8,10])%2==0]

array([ 2,  4,  6,  8, 10])

In [45]:
num[num%2==0]

array([10, 12])

In [46]:
np.dot(num,num)

534

In [47]:
arr = [0.23,0.09,1.2,1.24,9.99]
np.fix(arr)

array([0., 0., 1., 1., 9.])

In [48]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[10,11,12],[13,14,15],[16,17,18]])
arr3 = np.multiply(arr1,arr2)

In [49]:
np.append(arr1,arr2,axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [50]:
np.rint(arr)

array([ 0.,  0.,  1.,  1., 10.])

In [51]:
np.transpose(arr1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [52]:
x = np.arange(0,10)
x[x%2==1]

array([1, 3, 5, 7, 9])

In [53]:
np.where(x%2==0,0,x)

array([0, 1, 0, 3, 0, 5, 0, 7, 0, 9])

In [54]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)

In [55]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [56]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [57]:
np.concatenate([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [58]:
np.append(a,b,axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [59]:
np.r_[a,b]
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [60]:
np.repeat(a,3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7,
       7, 7, 8, 8, 8, 9, 9, 9])

In [61]:
np.tile(a,1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [62]:
np.intersect1d(np.array([1,2,3]),np.array([2,3,4])) 

array([2, 3])

In [63]:
np.setdiff1d(np.array([1,2,3]),np.array([2,3,4]))

array([1])

In [64]:
a = np.arange(15)
a[np.where((a>5) & (a<10))]

array([6, 7, 8, 9])

In [65]:
a.reshape(5,3)[:,[1,0,2]]

array([[ 1,  0,  2],
       [ 4,  3,  5],
       [ 7,  6,  8],
       [10,  9, 11],
       [13, 12, 14]])

In [66]:
a.reshape(5,3)[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [67]:
a.reshape(5,3)[::-1]

array([[12, 13, 14],
       [ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])

In [68]:
a.reshape(5,3)[:,::-1]

array([[ 2,  1,  0],
       [ 5,  4,  3],
       [ 8,  7,  6],
       [11, 10,  9],
       [14, 13, 12]])

In [69]:
np.random.randint(5,10,size=(5,3))

array([[7, 9, 5],
       [6, 9, 7],
       [6, 6, 8],
       [9, 6, 5],
       [5, 8, 6]])

In [70]:
np.random.random((5,3))

array([[0.68927201, 0.86936929, 0.26780382],
       [0.45674792, 0.26828131, 0.8370528 ],
       [0.27051466, 0.53006201, 0.17537266],
       [0.31496645, 0.8911091 , 0.18033628],
       [0.4943162 , 0.2122981 , 0.52087687]])

In [71]:
np.set_printoptions(precision=8)

In [72]:
np.random.random([3,3])/1e3

array([[0.0001601 , 0.00091906, 0.00099429],
       [0.00047705, 0.00030988, 0.0005072 ],
       [0.00028079, 0.00076384, 0.00010854]])

In [73]:
np.set_printoptions(suppress=True)

In [74]:
np.random.random([3,3])/1e3

array([[0.00051165, 0.00090977, 0.00021838],
       [0.0003631 , 0.00085497, 0.00071139],
       [0.00039294, 0.0002313 , 0.00038017]])

In [75]:
np.arange(101)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [76]:
# import sys
np.set_printoptions(threshold=6)
# np.set_printoptions(threshold=sys.maxsize)

In [77]:
np.arange(101)

array([  0,   1,   2, ...,  98,  99, 100])

In [78]:
iris = np.genfromtxt("Iris.csv",delimiter=",",dtype=None)
iris

C:\Users\aakas\Anaconda\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  """Entry point for launching an IPython kernel.


array([[b'Id', b'SepalLengthCm', b'SepalWidthCm', b'PetalLengthCm',
        b'PetalWidthCm', b'Species'],
       [b'1', b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'2', b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       ...,
       [b'148', b'6.5', b'3.0', b'5.2', b'2.0', b'Iris-virginica'],
       [b'149', b'6.2', b'3.4', b'5.4', b'2.3', b'Iris-virginica'],
       [b'150', b'5.9', b'3.0', b'5.1', b'1.8', b'Iris-virginica']],
      dtype='|S15')

In [79]:
[i[4] for i in iris]

[b'PetalWidthCm',
 b'0.2',
 b'0.2',
 b'0.2',
 b'0.2',
 b'0.2',
 b'0.4',
 b'0.3',
 b'0.2',
 b'0.2',
 b'0.1',
 b'0.2',
 b'0.2',
 b'0.1',
 b'0.1',
 b'0.2',
 b'0.4',
 b'0.4',
 b'0.3',
 b'0.3',
 b'0.3',
 b'0.2',
 b'0.4',
 b'0.2',
 b'0.5',
 b'0.2',
 b'0.2',
 b'0.4',
 b'0.2',
 b'0.2',
 b'0.2',
 b'0.2',
 b'0.4',
 b'0.1',
 b'0.2',
 b'0.1',
 b'0.2',
 b'0.2',
 b'0.1',
 b'0.2',
 b'0.2',
 b'0.3',
 b'0.3',
 b'0.2',
 b'0.6',
 b'0.4',
 b'0.3',
 b'0.2',
 b'0.2',
 b'0.2',
 b'0.2',
 b'1.4',
 b'1.5',
 b'1.5',
 b'1.3',
 b'1.5',
 b'1.3',
 b'1.6',
 b'1.0',
 b'1.3',
 b'1.4',
 b'1.0',
 b'1.5',
 b'1.0',
 b'1.4',
 b'1.3',
 b'1.4',
 b'1.5',
 b'1.0',
 b'1.5',
 b'1.1',
 b'1.8',
 b'1.3',
 b'1.5',
 b'1.2',
 b'1.3',
 b'1.4',
 b'1.4',
 b'1.7',
 b'1.5',
 b'1.0',
 b'1.1',
 b'1.0',
 b'1.2',
 b'1.6',
 b'1.5',
 b'1.6',
 b'1.5',
 b'1.3',
 b'1.3',
 b'1.3',
 b'1.2',
 b'1.4',
 b'1.2',
 b'1.0',
 b'1.3',
 b'1.2',
 b'1.3',
 b'1.3',
 b'1.1',
 b'1.3',
 b'2.5',
 b'1.9',
 b'2.1',
 b'1.8',
 b'2.2',
 b'2.1',
 b'1.7',
 b'1.8',
 b'1.8',
 

In [80]:
iris[:,:1]

array([[b'Id'],
       [b'1'],
       [b'2'],
       ...,
       [b'148'],
       [b'149'],
       [b'150']], dtype='|S15')

In [81]:
iris1 = np.genfromtxt("Iris.csv",delimiter=",",dtype='float',usecols=[1,2,3,4])
iris1[1:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       ...,
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [82]:
np.mean(iris1[1:,1])

3.0540000000000003

In [83]:
np.median(iris1[1:,1])

3.0

In [84]:
np.std(iris1[1:,1])

0.4321465800705435

In [85]:
np.max(iris1[1:,1])

4.4

In [86]:
iris2 = np.genfromtxt("Iris.csv",delimiter=",",dtype="object")
;iris2

TypeError: 'numpy.ndarray' object is not callable

In [ ]:
iris1[1:][iris1[1:,0] > 6]

In [ ]:
np.corrcoef(iris1[1:,0],iris1[1:,1])

In [ ]:
iris1[np.isnan(iris1)]

In [ ]:
np.unique(iris1[1:,0])

In [87]:
np.unique(np.array(["aakash","aakash","akshay","akshay"]),return_counts=True)

(array(['aakash', 'akshay'], dtype='<U6'), array([2, 2], dtype=int64))

In [ ]:
np.array([1,2,3]).astype("float")

In [ ]:
np.random.choice(a,150)

In [ ]:
import sys
np.set_printoptions(threshold=sys.maxsize)

In [89]:
import pandas as pd

In [117]:
import sys
np.set_printoptions(threshold=sys.maxsize)
pd.DataFrame(np.random.randint(1,7,35).reshape(7,5)).to_numpy()

array([[1, 2, 1, 5, 4],
       [3, 6, 5, 6, 1],
       [2, 3, 3, 3, 3],
       [4, 3, 2, 1, 5],
       [2, 6, 6, 2, 3],
       [1, 4, 2, 4, 6],
       [4, 6, 4, 6, 2]])

In [121]:
pd.DataFrame(iris1[1:])

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3