In [13]:
n = "3"
m = "2"
print(f"{n}{m}")

32


In [31]:
def j(y):
    print(''.join([str(x) for x in range(1,y)]))


In [33]:
j(4)

123


In [38]:
import numpy

my_array = numpy.array([[2, 5], [3, 7],[1, 3],[4, 0]])

print(numpy.min(my_array, axis = 0))         #Output : [1 0]
print(numpy.min(my_array, axis = 1))         #Output : [2 3 1 0]
print(numpy.min(my_array, axis = None))      #Output : 0
print(numpy.min(my_array))                   #Output : 0


[1 0]
[2 3 1 0]
0
0


In [42]:
my_array

array([[2, 5],
       [3, 7],
       [1, 3],
       [4, 0]])

In [43]:
print(numpy.max(my_array, axis = 0))        
print(numpy.max(my_array, axis = 1))        
print(numpy.max(my_array, axis = None))     
print(numpy.max(my_array))                  


[4 7]
[5 7 3 4]
7
7
