In [1]:
import numpy as np
import pandas as pd
import datetime as dt
# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_columns',None)
# pd.set_option('display.width',None)

In [30]:
df = pd.read_excel("Data_and_Train_Data/train_data.xlsx")
# df1 = pd.read_excel("Data_and_Train_Data/Master.xlsx")
# df2 = pd.read_excel("Data_and_Train_Data/More-Attributes.xlsx")

In [57]:
# df["ID"] = pd.DataFrame(np.arange(1,len(df)+1))

In [58]:
# df = df.reindex(columns = ['Book_Stall', 'Genre', 'Week_Date', 'Sales_in_a_week', 'Holiday'])

In [31]:
df = df[["Week_Date","Sales_in_a_week"]]
df.columns = ["ds","y"]
df = df[df["y"] > 0]
df

ds         y
0      2010-02-05  24924.50
1      2010-02-12  46039.49
2      2010-02-19  41595.55
3      2010-02-26  19403.54
4      2010-03-05  21827.90
...           ...       ...
293699 2012-07-13      0.02
293700 2012-07-20      0.02
293701 2012-08-24      0.02
293702 2012-08-31      0.02
293703 2012-09-07      0.02

[292824 rows x 2 columns]

In [32]:
test = pd.read_excel("test_sales.xlsx")

In [33]:
# test["Holiday"].replace({False:0,True:1},inplace=True)
test = test[[ 'Week_Date']]
test.columns = ["ds"]
test

ds
0     2012-11-02
1     2012-11-09
2     2012-11-16
3     2012-11-23
4     2012-11-30
...          ...
80016 2013-07-05
80017 2013-07-12
80018 2013-07-19
80019 2013-07-26
80020 2013-07-26

[80021 rows x 1 columns]

In [34]:
from fbprophet import Prophet

In [35]:
m = Prophet()

In [36]:
m.fit(df)

INFO:fbprophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.


In [37]:
predict = m.predict(test)
predict

ds         trend    yhat_lower    yhat_upper   trend_lower  \
0     2012-11-02  17553.001144 -12761.626447  47804.543784  17553.001144   
1     2012-11-02  17553.001144 -14014.245246  46375.601390  17553.001144   
2     2012-11-02  17553.001144 -13061.674560  47822.746121  17553.001144   
3     2012-11-02  17553.001144 -12689.302062  46670.979807  17553.001144   
4     2012-11-02  17553.001144 -13481.608223  49925.200440  17553.001144   
...          ...           ...           ...           ...           ...   
80016 2013-07-26  17808.410750 -11865.040457  47295.066158  16775.536063   
80017 2013-07-26  17808.410750 -14768.302047  46647.087305  16775.536063   
80018 2013-07-26  17808.410750 -12395.017282  49001.547709  16775.536063   
80019 2013-07-26  17808.410750 -15591.975410  45363.175736  16775.536063   
80020 2013-07-26  17808.410750 -10866.387739  48675.108042  16775.536063   

        trend_upper  additive_terms  additive_terms_lower  \
0      17553.001144     -597.939699           -597.939699   
1      17553.001144     -597.939699           -597.939699   
2      17553.001144     -597.939699           -597.939699   
3      17553.001144     -597.939699           -597.939699   
4      17553.001144     -597.939699           -597.939699   
...             ...             ...                   ...   
80016  18732.647013     -560.375097           -560.375097   
80017  18732.647013     -560.375097           -560.375097   
80018  18732.647013     -560.375097           -560.375097   
80019  18732.647013     -560.375097           -560.375097   
80020  18732.647013     -560.375097           -560.375097   

       additive_terms_upper      yearly  yearly_lower  yearly_upper  \
0               -597.939699 -597.939699   -597.939699   -597.939699   
1               -597.939699 -597.939699   -597.939699   -597.939699   
2               -597.939699 -597.939699   -597.939699   -597.939699   
3               -597.939699 -597.939699   -597.939699   -597.939699   
4               -597.939699 -597.939699   -597.939699   -597.939699   
...                     ...         ...           ...           ...   
80016           -560.375097 -560.375097   -560.375097   -560.375097   
80017           -560.375097 -560.375097   -560.375097   -560.375097   
80018           -560.375097 -560.375097   -560.375097   -560.375097   
80019           -560.375097 -560.375097   -560.375097   -560.375097   
80020           -560.375097 -560.375097   -560.375097   -560.375097   

       multiplicative_terms  multiplicative_terms_lower  \
0                       0.0                         0.0   
1                       0.0                         0.0   
2                       0.0                         0.0   
3                       0.0                         0.0   
4                       0.0                         0.0   
...                     ...                         ...   
80016                   0.0                         0.0   
80017                   0.0                         0.0   
80018                   0.0                         0.0   
80019                   0.0                         0.0   
80020                   0.0                         0.0   

       multiplicative_terms_upper          yhat  
0                             0.0  16955.061445  
1                             0.0  16955.061445  
2                             0.0  16955.061445  
3                             0.0  16955.061445  
4                             0.0  16955.061445  
...                           ...           ...  
80016                         0.0  17248.035653  
80017                         0.0  17248.035653  
80018                         0.0  17248.035653  
80019                         0.0  17248.035653  
80020                         0.0  17248.035653  

[80021 rows x 16 columns]

In [38]:
predict[["yhat"]].max()

yhat    23810.358936
dtype: float64

In [39]:
Sales = pd.read_csv("Submission_format_Sales.csv")
Sales["Sales_in_a_week"] = predict["yhat"]
Sales

ID  Sales_in_a_week
0          1     16955.061445
1          2     16955.061445
2          3     16955.061445
3          4     16955.061445
4          5     16955.061445
...      ...              ...
80016  80017     17248.035653
80017  80018     17248.035653
80018  80019     17248.035653
80019  80020     17248.035653
80020  80021     17248.035653

[80021 rows x 2 columns]

In [40]:
# Sales.to_csv("D:\\Skillenza_Bootcamp\\ML Level3\\Problem2\\Sales_fb.csv",index=False)

In [41]:
df

ds         y
0      2010-02-05  24924.50
1      2010-02-12  46039.49
2      2010-02-19  41595.55
3      2010-02-26  19403.54
4      2010-03-05  21827.90
...           ...       ...
293699 2012-07-13      0.02
293700 2012-07-20      0.02
293701 2012-08-24      0.02
293702 2012-08-31      0.02
293703 2012-09-07      0.02

[292824 rows x 2 columns]

In [42]:
df.ds.values.reshape(-1, 1)

array([['2010-02-05T00:00:00.000000000'],
       ['2010-02-12T00:00:00.000000000'],
       ['2010-02-19T00:00:00.000000000'],
       ...,
       ['2012-08-24T00:00:00.000000000'],
       ['2012-08-31T00:00:00.000000000'],
       ['2012-09-07T00:00:00.000000000']], dtype='datetime64[ns]')

In [45]:
df['y'].values.reshape(-1, 1)

array([[2.492450e+04],
       [4.603949e+04],
       [4.159555e+04],
       ...,
       [2.000000e-02],
       [2.000000e-02],
       [2.000000e-02]])

In [49]:
# pd.options.display.float_format = '{:.2f}'.format
df.ds.values.astype(float).reshape(-1, 1)

array([[1.2653280e+18],
       [1.2659328e+18],
       [1.2665376e+18],
       ...,
       [1.3457664e+18],
       [1.3463712e+18],
       [1.3469760e+18]])

In [54]:
# pd.options.display.float_format = '{:.2f}'.format
test.ds.values.astype(float).reshape(-1,1)

array([[1.3518144e+18],
       [1.3524192e+18],
       [1.3530240e+18],
       ...,
       [1.3741920e+18],
       [1.3747968e+18],
       [1.3747968e+18]])

In [50]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [51]:
lr.fit(df.ds.values.reshape(-1, 1),df['y'].values.reshape(-1, 1))

LinearRegression()

In [60]:
predict_lr = pd.DataFrame(lr.predict(test.ds.values.astype(float).reshape(-1,1)))
predict_lr

0
0     17114.80
1     17113.99
2     17113.18
3     17112.37
4     17111.56
...        ...
80016 17086.47
80017 17085.66
80018 17084.85
80019 17084.04
80020 17084.04

[80021 rows x 1 columns]

In [62]:
Sales_lr = pd.read_csv("Submission_format_Sales.csv")
Sales_lr["Sales_in_a_week"] = predict_lr[0]
Sales_lr
# Sales_lr.to_csv("D:\\Skillenza_Bootcamp\\ML Level3\\Problem2\\Sales_lr.csv",index=False)

In [53]:
# df1 = df[["Week_Date","Sales_in_a_week"]]
# df1.columns = ["ds","y"]
# df1

# import matplotlib.pyplot as plt
# # figsize = (12,8)
# df1.plot(x="ds",y='y')


# from fbprophet import Prophet
# m = Prophet()

# m.fit(df1)


# test1 = test[["Week_Date"]]
# test1.columns = ["ds"]
# test1

# predict = m.predict(test1)

# test["Sales_in_a_week"] =  predict[["yhat"]]
# test2 = test[["ID","Sales_in_a_week"]]
# test2.to_csv("D:\\Skillenza_Bootcamp\\ML Level3\\Problem2\\estimate_fb1.csv",index = False)

In [1]:
# df_days = df.loc[:,"Week_Date"]
# df_Sales = df.loc[:,"Sales_in_a_week"]
# df_days

# days = []
# sales = []
# days = [[x] for x in df["Week_Date"].dt.day]
# sales = [float (j) for j in df_Sales]


# from sklearn.svm import SVR
# # Create the 3 Support Vector Regression Models
# # Create and Train a SVR Model using a linear kernel
# lin_svr = SVR(kernel="linear",C=1000.0)
# lin_svr.fit(days,sales)

# # Create and Train a SVR Model using a Polynomial kernel
# poly_svr = SVR(kernel="poly",C=1000.0,degree=2)
# poly_svr.fit(days,sales)

# # Create and Train a SVR Model using a rbf kernel
# rbf_svr = SVR(kernel="rbf",C=1000.0)
# rbf_svr.fit(days,sales)

# # plot the models on a graph to see which has the best fit to the original data
# plt.figure(figsize=(16,8))
# plt.scatter(days,sales,color="red",label="Data")
# plt.plot(days,rbf_svr.predict(days),color="green",label="RBF Model")
# plt.plot(days,poly_svr.predict(days),color="orange",label="Polynomial Model")
# plt.plot(days,lin_svr.predict(days),color="blue",label="Linear Model")
# plt.legend()
# plt.show()

In [7]:
# df1
# df2
# df1.columns = ['Book_Stall', 'Size']
# df3 = pd.merge(df,df1,on = "Book_Stall")
# df2.isna().sum()
# df4 = df2.drop(columns=["Campaign 2","Campaign 1"],axis=1).fillna(df2["Consumer Price Index"].median())
# df4.columns = ["Book_Stall", 'Week_Date', 'Consumer Price Index', 'Holiday']
# df_new = pd.merge(df3,df4,on = ["Book_Stall","Week_Date","Holiday"])
# df_new
# df_new["Holiday"].replace({False:0,True:1},inplace=True)
# df_new = df_new.reindex(columns = ['Book_Stall', 'Genre', 'Week_Date', 'Holiday','Size', 'Consumer Price Index','Sales_in_a_week' ])

In [8]:
# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_columns',None)
# pd.set_option('display.width',None)

In [30]:
# df["Holiday"].replace({False:0,True:1},inplace=True)

In [10]:
# stalls = []
# for i in range(0,30):
#     stalls.append(df[df["Book_Stall"] == i+1])

In [12]:
# for i in range(0,30):
#     stalls[i] = stalls[i].reindex(columns=['ID','Book_Stall', 'Genre', 'Week_Date', 'Week_Date_New','Holiday', 'Sales_in_a_week'])

C:\Users\aakas\Anaconda\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [29]:
# Estimate = pd.DataFrame(columns=["ID","Sales_in_a_week"])
# Estimate["ID"] =test1.iloc[:,0]
# Estimate["Sales_in_a_week"] =pd.DataFrame(lr.predict(test1))[0]
# Estimate.to_csv("D:\\Skillenza_Bootcamp\\ML Level3\\Problem2\\estimate_predict.csv")